name: fluent_2_web_example
description: "Storybook for the Fluent 2 web components."
publish_to: 'none'
version: 1.0.0+1
resolution: workspace

environment:
  sdk: ^3.12.2

dependencies:
  fluent_2_web:
    path: ..
  flutter:
    sdk: flutter
  storybook_flutter: ^0.14.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
