#!/usr/bin/env python3
"""One-shot codemod: give every alias colour token a per-token override hook.

Fluent React lets a consumer override ONE of ~467 theme keys for ONE subtree via
a nested `<FluentProvider theme={{colorBrandBackground: '#780510'}}>`. Core could
only replace the whole `FluentColors` object, so this rewrites every alias getter
to consult an override map first:

    Color get neutralForeground1 => _d ? _white : _g(14);
    ->
    Color get neutralForeground1 =>
        _o(FluentColorToken.neutralForeground1, _d ? _white : _g(14));

The one-line-per-token shape is preserved deliberately — it is what keeps every
value checkable against upstream `alias/lightColor.ts`.

Committed rather than run-and-discarded so the transform is auditable. It is
idempotent: getters already wrapped in `_o(` are skipped, so a re-run is a no-op.

Run:  python3 packages/fluent_2_core/tool/add_token_overrides.py
Gate: the existing test suite. If it still passes, the rewrite preserved every
      value; that is the whole point of doing this before any component exists.
"""

import pathlib
import re
import subprocess
import sys

HERE = pathlib.Path(__file__).parent
TOKENS = HERE.parent / "lib" / "src" / "tokens"
ALIAS = TOKENS / "alias_colors.dart"
VARIANTS = TOKENS / "theme_variants.dart"
TOKEN_ENUM = TOKENS / "color_token.dart"

# `Color get NAME => <body>;` — the body never contains a semicolon, so a
# negated class is enough and it spans wrapped lines without needing DOTALL.
GETTER = re.compile(r"^(?P<indent>[ ]{2})Color get (?P<name>\w+) =>(?P<body>[^;]*);",
                    re.M)


def read(p):
    return p.read_text()


def collect_names(src):
    """Getter names in declaration order, de-duplicated."""
    seen, out = set(), []
    for m in GETTER.finditer(src):
        n = m.group("name")
        if n not in seen:
            seen.add(n)
            out.append(n)
    return out


def wrap_getters(src, known):
    """Route each getter body through `_o`. Idempotent."""
    count = [0]

    def repl(m):
        name, body = m.group("name"), m.group("body").strip()
        if body.startswith("applyOverride("):
            return m.group(0)
        if name not in known:
            raise SystemExit(f"FAIL: getter {name!r} has no enum value")
        count[0] += 1
        return (f"{m.group('indent')}Color get {name} =>\n"
                f"{m.group('indent')}    applyOverride("
                f"FluentColorToken.{name}, {body});")

    return GETTER.sub(repl, src), count[0]


def gen_enum(names):
    lines = [
        "// GENERATED BY tool/add_token_overrides.py — DO NOT EDIT BY HAND.",
        "",
        "/// Identifies a single alias colour token.",
        "///",
        "/// The Dart counterpart of a key in Fluent React's flat `Theme` object.",
        "/// Exists so a subtree can override one token without replacing the whole",
        "/// palette — see `FluentThemeOverride`.",
        "enum FluentColorToken {",
    ]
    for n in names:
        lines.append(f"  /// The `{n}` alias token.")
        lines.append(f"  {n},")
    lines += ["}", ""]
    return "\n".join(lines)


def patch_base(src, names):
    """Add the overrides field, `_o`, `resolve`, `withOverrides` and equality."""
    if "FluentColorToken" in src:
        print("  base class already patched, skipping")
        return src

    src = src.replace(
        "import 'global_colors.dart';",
        "import 'color_token.dart';\nimport 'global_colors.dart';", 1)

    src = src.replace(
        """  const FluentColors({
    this.brightness = Brightness.light,
    this.brand = FluentBrandRamp.web,
  });""",
        """  const FluentColors({
    this.brightness = Brightness.light,
    this.brand = FluentBrandRamp.web,
    this.overrides,
  });""", 1)

    arms = "\n".join(f"    FluentColorToken.{n} => {n}," for n in names)
    members = f'''  final Brightness brightness;
  final FluentBrandRamp brand;

  /// Per-token overrides applied before the computed value.
  ///
  /// The counterpart of a `PartialTheme` handed to a nested `FluentProvider`
  /// upstream. Usually set through `FluentThemeOverride` rather than directly.
  final Map<FluentColorToken, Color>? overrides;

  /// Override lookup. Every alias getter routes through this.
  ///
  /// Protected rather than private because the theme variants live in their own
  /// library, and Dart privacy is library-scoped. Consumers want [resolve].
  @protected
  @pragma('vm:prefer-inline')
  Color applyOverride(FluentColorToken token, Color computed) =>
      overrides?[token] ?? computed;

  /// Resolves any token by identity — the analogue of `tokens[key]` upstream.
  Color resolve(FluentColorToken token) => switch (token) {{
{arms}
  }};

  /// This palette with [extra] merged over any existing [overrides].
  ///
  /// Overridden by each variant so the concrete theme survives: overriding a
  /// token on high contrast must not silently demote it to the default palette.
  FluentColors withOverrides(Map<FluentColorToken, Color> extra) => FluentColors(
    brightness: brightness,
    brand: brand,
    overrides: {{...?overrides, ...extra}},
  );

  bool get _d => brightness == Brightness.dark;'''

    src = src.replace("""  final Brightness brightness;
  final FluentBrandRamp brand;

  bool get _d => brightness == Brightness.dark;""", members, 1)

    # FluentColors already defines == / hashCode over (runtimeType, brightness,
    # brand). Extend that in place rather than appending a second pair —
    # `overrides` must participate, or FluentThemeOverride would rebuild its
    # whole subtree on every build (two palettes differing only in overrides
    # would compare equal, so updateShouldNotify could not tell them apart).
    existing = """  bool operator ==(Object other) =>
      other is FluentColors &&
      other.runtimeType == runtimeType &&
      other.brightness == brightness &&
      other.brand == brand;

  @override
  int get hashCode => Object.hash(runtimeType, brightness, brand);"""
    if existing not in src:
        raise SystemExit("FAIL: FluentColors equality is not in the expected "
                         "shape; refusing to guess")
    replacement = """  bool operator ==(Object other) =>
      other is FluentColors &&
      other.runtimeType == runtimeType &&
      other.brightness == brightness &&
      other.brand == brand &&
      _sameOverrides(other.overrides, overrides);

  @override
  int get hashCode => Object.hash(
    runtimeType,
    brightness,
    brand,
    // Map has no structural hashCode. Length plus the unordered key set keeps
    // unequal palettes apart without depending on insertion order.
    overrides?.length ?? 0,
    Object.hashAllUnordered(overrides?.keys ?? const <FluentColorToken>[]),
  );

  static bool _sameOverrides(
    Map<FluentColorToken, Color>? a,
    Map<FluentColorToken, Color>? b,
  ) {
    if (identical(a, b)) return true;
    if (a == null || b == null || a.length != b.length) return false;
    for (final e in a.entries) {
      if (b[e.key] != e.value) return false;
    }
    return true;
  }"""
    src = src.replace(existing, replacement, 1)
    return src

    return src


def patch_variants(src):
    """Thread `overrides` through the subclass constructors and withOverrides."""
    if "super.overrides" in src:
        print("  variants already patched, skipping")
        return src

    src = src.replace("import 'alias_colors.dart';",
                      "import 'alias_colors.dart';\nimport 'color_token.dart';", 1)

    src = src.replace(
        "  const FluentTeamsDarkColors({super.brand = FluentBrandRamp.teams})\n"
        "    : super(brightness: Brightness.dark);",
        "  const FluentTeamsDarkColors({\n"
        "    super.brand = FluentBrandRamp.teams,\n"
        "    super.overrides,\n"
        "  }) : super(brightness: Brightness.dark);\n"
        "\n"
        "  @override\n"
        "  FluentTeamsDarkColors withOverrides("
        "Map<FluentColorToken, Color> extra) =>\n"
        "      FluentTeamsDarkColors(\n"
        "        brand: brand,\n"
        "        overrides: {...?overrides, ...extra},\n"
        "      );", 1)

    src = src.replace(
        "  const FluentHighContrastColors() : super(brightness: Brightness.dark);",
        "  const FluentHighContrastColors({super.overrides})\n"
        "    : super(brightness: Brightness.dark);\n"
        "\n"
        "  @override\n"
        "  FluentHighContrastColors withOverrides("
        "Map<FluentColorToken, Color> extra) =>\n"
        "      FluentHighContrastColors(overrides: {...?overrides, ...extra});", 1)
    return src


def main():
    alias = read(ALIAS)
    names = collect_names(alias)
    print(f"found {len(names)} alias tokens")
    if len(names) < 180:
        print(f"FAIL: only {len(names)} tokens found; the getter regex is wrong",
              file=sys.stderr)
        return 1

    TOKEN_ENUM.write_text(gen_enum(names))
    print(f"wrote color_token.dart with {len(names)} enum values")

    alias = patch_base(alias, names)
    alias, n = wrap_getters(alias, set(names))
    ALIAS.write_text(alias)
    print(f"alias_colors.dart:  wrapped {n} getters")

    variants = patch_variants(read(VARIANTS))
    variants, n = wrap_getters(variants, set(names))
    VARIANTS.write_text(variants)
    print(f"theme_variants.dart: wrapped {n} getters")

    r = subprocess.run(["dart", "format", str(ALIAS), str(VARIANTS),
                        str(TOKEN_ENUM)], capture_output=True, text=True)
    if r.returncode != 0:
        print(f"FAIL: dart format rejected the rewrite:\n{r.stderr}",
              file=sys.stderr)
        return 1
    print(r.stdout.strip())
    return 0


if __name__ == "__main__":
    sys.exit(main())
