#!/usr/bin/env python3
"""Generate the Dart token files that core never ported, from figma_tokens.json.

Emits four files under lib/src/tokens/:
    shared_colors.dart   49 shared ramps x 12 shades (the substrate)
    status_colors.dart   41 status tokens (danger/severe/success/warning + presence)
    palette_colors.dart  151 persona/accent tokens across 35 families
    materials.dart       6 acrylic material tokens

These are generated, not hand-written, because a mistyped digit in 700+ colors
is invisible in review and permanent in output. Re-run after re-extracting:

    python3 packages/fluent_2_core/tool/generate_tokens.py

Every emitted member carries a doc comment naming its Figma variable, because
analysis_options.yaml promotes public_member_api_docs to an error.
"""

import json
import pathlib
import re
import subprocess
import sys

HERE = pathlib.Path(__file__).parent
LIB = HERE.parent / "lib" / "src" / "tokens"

BANNER = """// GENERATED BY tool/generate_tokens.py — DO NOT EDIT BY HAND.
//
// Source: tool/figma_tokens.json, extracted from the official Microsoft
// "Fluent 2 Web (Community)" Figma file (key Heyk4N9SnwfIzupHlk3l7s) and
// resolved to literals by tool/merge_figma_tokens.py.
//
// To change a value, fix it upstream and re-run the generator.
"""

SHADES = ["Shade 50", "Shade 40", "Shade 30", "Shade 20", "Shade 10",
          "Primary", "Tint 10", "Tint 20", "Tint 30", "Tint 40", "Tint 50",
          "Tint 60"]


def load():
    with open(HERE / "figma_tokens.json") as f:
        return json.load(f)


def dart_color(hexstr):
    """'#rrggbb' or '#rrggbbaa' -> const Color(0xAARRGGBB)."""
    h = hexstr.lstrip("#")
    if len(h) == 6:
        a = "ff"
    elif len(h) == 8:
        h, a = h[:6], h[6:]
    else:
        raise ValueError(f"unexpected hex {hexstr!r}")
    return f"Color(0x{a}{h})".upper().replace("COLOR(0X", "Color(0x")


def camel(*parts):
    """Join name parts into lowerCamelCase, preserving trailing digits."""
    words = []
    for p in parts:
        words += [w for w in re.split(r"[^A-Za-z0-9]+", p) if w]
    if not words:
        raise ValueError("empty identifier")
    out = words[0][0].lower() + words[0][1:]
    for w in words[1:]:
        out += w[0].upper() + w[1:]
    if out[0].isdigit():
        out = "n" + out
    return out


# --------------------------------------------------------------- shared ramps

def gen_shared(g):
    entries = {}
    for key, val in g.items():
        if not key.startswith("Colors/Shared/"):
            continue
        _, _, family, shade = key.split("/", 3)
        entries.setdefault(family, {})[shade] = val["Value"]

    families = sorted(entries)
    lines = [BANNER, "", "import 'package:flutter/widgets.dart';", "",
             "/// A family in the Fluent 2 shared colour ramp.",
             "///",
             "/// These are the raw ramps the persona, presence and accent tokens",
             "/// alias into. Source: Figma ` Global` collection, `Colors/Shared/*`.",
             "enum FluentSharedColor {"]
    for f in families:
        lines.append(f"  /// The `{f}` shared ramp.")
        lines.append(f"  {camel(f)},")
    lines += ["}", "",
              "/// The twelve stops of one shared colour ramp.",
              "@immutable",
              "class FluentSharedShades {",
              "  /// Creates a ramp from its twelve stops.",
              "  const FluentSharedShades({"]
    for s in SHADES:
        lines.append(f"    required this.{camel(s)},")
    lines += ["  });", ""]
    for s in SHADES:
        lines.append(f"  /// The `{s}` stop.")
        lines.append(f"  final Color {camel(s)};")
    lines += ["}", "",
              "/// The 49 shared colour ramps, keyed by family.",
              "abstract final class FluentSharedRamp {",
              "  /// Every shared ramp, keyed by [FluentSharedColor].",
              "  static const Map<FluentSharedColor, FluentSharedShades> all = {"]
    for f in families:
        lines.append(f"    FluentSharedColor.{camel(f)}: FluentSharedShades(")
        for s in SHADES:
            lines.append(f"      {camel(s)}: {dart_color(entries[f][s])},")
        lines.append("    ),")
    lines += ["  };", "",
              "  /// The ramp for [family]. Never null — every family is present.",
              "  static FluentSharedShades of(FluentSharedColor family) =>",
              "      all[family]!;",
              "}", ""]
    return "\n".join(lines), len(families)


# -------------------------------------------------------------------- status

def gen_status(mode):
    keys = sorted(k for k in mode if k.startswith("Status/"))
    lines = [BANNER, "", "import 'package:flutter/widgets.dart';", "",
             "/// The Fluent 2 status colour layer — danger, severe, success and",
             "/// warning, plus the three presence states.",
             "///",
             "/// Resolves against [brightness] exactly as `FluentColors` does,",
             "/// so light and dark sit on one line and stay checkable against the",
             "/// Figma `Mode` collection's `Status/*` variables.",
             "///",
             "/// Note these follow the Figma file, which disagrees with the shipped",
             "/// `@fluentui/react-components` TypeScript on four dark-mode values",
             "/// (success foreground-inverted, and warning foreground1/foreground3/",
             "/// stroke1). See doc/token-divergences.md.",
             "@immutable",
             "class FluentStatusColors {",
             "  /// Creates the status layer for [brightness].",
             "  const FluentStatusColors({this.brightness = Brightness.light});", "",
             "  /// Which theme these tokens resolve for.",
             "  final Brightness brightness;", "",
             "  bool get _d => brightness == Brightness.dark;", ""]
    for k in keys:
        name = camel(*k.split("/")[1:])
        light, dark = mode[k]["Light"], mode[k]["Dark"]
        lines.append(f"  /// Figma `{k}`.")
        if light == dark:
            lines.append(f"  Color get {name} => const {dart_color(light)};")
        else:
            lines.append(f"  Color get {name} =>")
            lines.append(f"      _d ? const {dart_color(dark)} "
                         f": const {dart_color(light)};")
    lines += ["}", ""]
    return "\n".join(lines), len(keys)


# ------------------------------------------------------------------- palette

def gen_palette(mode):
    entries = {}
    for k in mode:
        if not k.startswith("Palette/"):
            continue
        _, family, rest = k.split("/", 2)
        entries.setdefault(rest, {})[family] = mode[k]

    families = sorted({f for v in entries.values() for f in v})
    total = [t for t, v in entries.items() if len(v) == len(families)]
    partial = [t for t in entries if t not in total]

    lines = [BANNER, "", "import 'package:flutter/widgets.dart';", "",
             "/// A persona / accent colour family.",
             "///",
             "/// Source: Figma `Mode` collection, `Palette/*`. Upstream calls these",
             "/// `colorPalette*`; they back avatars, presence, badges and tags.",
             "enum FluentPaletteFamily {"]
    for f in families:
        lines.append(f"  /// The `{f}` palette family.")
        lines.append(f"  {camel(f)},")
    lines += ["}", "",
              "/// The Fluent 2 palette colour layer.",
              "///",
              "/// Accessors marked as returning a nullable [Color] are not defined",
              "/// for every family upstream — only the extended families carry the",
              "/// full background/foreground/stroke set. Returning null rather than",
              "/// inventing a value keeps the port honest.",
              "@immutable",
              "class FluentPaletteColors {",
              "  /// Creates the palette layer for [brightness].",
              "  const FluentPaletteColors({this.brightness = Brightness.light});", "",
              "  /// Which theme these tokens resolve for.",
              "  final Brightness brightness;", "",
              "  bool get _d => brightness == Brightness.dark;", ""]

    def emit_map(token, nullable):
        ident = camel(*token.split("/"))
        per = entries[token]
        lines.append(f"  /// Figma `Palette/<family>/{token}`.")
        ret = "Color?" if nullable else "Color"
        bang = "" if nullable else "!"
        lines.append(f"  {ret} {ident}(FluentPaletteFamily family) =>")
        lines.append(f"      (_d ? _{ident}Dark : _{ident}Light)[family]{bang};")
        lines.append("")
        for brightness, key in (("Light", "Light"), ("Dark", "Dark")):
            lines.append(f"  static const Map<FluentPaletteFamily, Color> "
                         f"_{ident}{brightness} = {{")
            for f in families:
                if f in per:
                    lines.append(f"    FluentPaletteFamily.{camel(f)}: "
                                 f"{dart_color(per[f][key])},")
            lines.append("  };")
            lines.append("")

    for t in sorted(total):
        emit_map(t, nullable=False)
    for t in sorted(partial):
        emit_map(t, nullable=True)

    lines += ["}", ""]
    return "\n".join(lines), sum(len(v) for v in entries.values()), total, partial


# ------------------------------------------------------------------ materials

def gen_materials(mode):
    keys = sorted(k for k in mode if k.startswith("Material/Acrylic/"))
    lines = [BANNER, "", "import 'package:flutter/widgets.dart';", "",
             "/// The Fluent 2 Acrylic material.",
             "///",
             "/// Acrylic is a translucent, blurred surface: a blurred backdrop with",
             "/// a tint painted over it.",
             "///",
             "/// [backgroundBlur] is a **blur radius in logical pixels**, as Figma",
             "/// and CSS `filter: blur()` express it — NOT a Gaussian sigma. Flutter's",
             "/// `ImageFilter.blur` takes sigma, so halve it: `sigma = radius / 2`.",
             "/// Passing the radius straight through doubles the blur.",
             "///",
             "/// Distinct from `FluentWindowsAcrylic` in `elevation.dart`, which is",
             "/// WinUI's effect-graph recipe for the same visual effect.",
             "@immutable",
             "class FluentAcrylic {",
             "  /// Creates the acrylic material for [brightness].",
             "  const FluentAcrylic({this.brightness = Brightness.light});", "",
             "  /// Which theme these tokens resolve for.",
             "  final Brightness brightness;", "",
             "  bool get _d => brightness == Brightness.dark;", ""]
    for k in keys:
        name = camel(*k.split("/")[2:])
        light, dark = mode[k]["Light"], mode[k]["Dark"]
        lines.append(f"  /// Figma `{k}`.")
        if isinstance(light, (int, float)):
            if light == dark:
                lines.append(f"  double get {name} => {float(light)};")
            else:
                lines.append(f"  double get {name} => "
                             f"_d ? {float(dark)} : {float(light)};")
        elif light == dark:
            lines.append(f"  Color get {name} => const {dart_color(light)};")
        else:
            lines.append(f"  Color get {name} =>")
            lines.append(f"      _d ? const {dart_color(dark)} "
                         f": const {dart_color(light)};")
    lines += ["}", ""]
    return "\n".join(lines), len(keys)


def main():
    d = load()
    mode, g = d["Mode"], d[" Global"]

    shared, nfam = gen_shared(g)
    (LIB / "shared_colors.dart").write_text(shared)
    print(f"shared_colors.dart   {nfam} families x {len(SHADES)} shades "
          f"= {nfam * len(SHADES)} colours")

    status, nstatus = gen_status(mode)
    (LIB / "status_colors.dart").write_text(status)
    print(f"status_colors.dart   {nstatus} tokens")

    palette, npal, total, partial = gen_palette(mode)
    (LIB / "palette_colors.dart").write_text(palette)
    print(f"palette_colors.dart  {npal} tokens; "
          f"{len(total)} total accessors, {len(partial)} partial (nullable)")
    print(f"                     total:   {sorted(total)}")
    print(f"                     partial: {sorted(partial)}")

    materials, nmat = gen_materials(mode)
    (LIB / "materials.dart").write_text(materials)
    print(f"materials.dart       {nmat} tokens")

    print(f"\ntotal generated: {nfam * len(SHADES) + nstatus + npal + nmat} values")

    # `melos run format` uses --set-exit-if-changed, so unformatted generated
    # output turns CI red. Formatting here keeps regeneration a no-op diff.
    written = [str(LIB / f) for f in ("shared_colors.dart", "status_colors.dart",
                                      "palette_colors.dart", "materials.dart")]
    r = subprocess.run(["dart", "format", *written],
                       capture_output=True, text=True)
    if r.returncode != 0:
        print(f"FAIL: dart format rejected the generated output:\n{r.stderr}",
              file=sys.stderr)
        return 1
    print(r.stdout.strip())
    return 0


if __name__ == "__main__":
    sys.exit(main())
