name: fluent_2_fonts_android
description: "Native Android font-family descriptors for Fluent 2."
version: 0.0.1
repository: https://github.com/B1Digital/fluent_ui_2_flutter
issue_tracker: https://github.com/B1Digital/fluent_ui_2_flutter/issues
resolution: workspace

environment:
  sdk: ^3.12.2
