import '../shell/catalog.dart';

/// The Package Maturity Levels page.
const DocsPage packageMaturityLevelsPage = DocsPage(
  id: 'concepts-package-maturity-levels',
  title: 'Package Maturity Levels',
  description: '',
  source: 'lib/pages/concepts_package_maturity_levels.dart',
  sections: <DocsSection>[],
  markdown: _markdown,
);

/// The page's source, as upstream publishes it.
const String _markdown =
    '# Package Maturity Levels\n'
    '\n'
    'This document explains the different maturity levels of '
    'Fluent UI v9 packages to help you make informed '
    'decisions about which components to use in your '
    'applications.\n'
    '\n'
    '## Overview\n'
    '\n'
    'Fluent UI v9 packages are categorized into four main '
    'maturity levels that indicate their stability and '
    'readiness for production use:\n'
    '\n'
    '-   **🟢 Stable**: Production-ready packages with stable '
    'APIs\n'
    '-   **🟡 Preview**: Early access packages in development '
    'with the intention to become stable\n'
    '-   **🔵 Compat**: Fluent UI v8 packages adapted to use '
    'v9 dependencies and APIs\n'
    '-   **🔴 Deprecated**: Unsupported packages with '
    'available alternatives\n'
    '\n'
    '## Package Categories\n'
    '\n'
    '### 🟢 Stable Packages\n'
    '\n'
    '**Characteristics:**\n'
    '\n'
    '-   Production-ready with stable APIs\n'
    '-   Full support and maintenance\n'
    '-   Version format: `9.x.x`\n'
    '-   Available from `@fluentui/react-components` suite\n'
    '-   Naming convention: `@fluentui/react-<name>`\n'
    '\n'
    '**Examples:** `@fluentui/react-button`, '
    '`@fluentui/react-text`\n'
    '\n'
    '**Import path:** `@fluentui/react-components`\n'
    '\n'
    '**When to use:** For all production applications where '
    'stability and long-term support are important.\n'
    '\n'
    '---\n'
    '\n'
    '### 🟡 Preview Packages\n'
    '\n'
    '**Characteristics:**\n'
    '\n'
    '-   Early access components not yet part of the stable '
    'suite\n'
    '-   May introduce breaking changes\n'
    '-   Active development with intention to become stable\n'
    '-   Version format: `0.x.x` (Note: translates to '
    '`0.major.(minor|patch)`)\n'
    '-   Not available from `@fluentui/react-components` '
    'suite\n'
    '-   Naming convention: `@fluentui/react-<name>-preview` '
    '(with `-preview` suffix)\n'
    '\n'
    '**Examples:** `@fluentui/react-nav-preview`\n'
    '\n'
    '**Import path:** `@fluentui/react-<name>-preview`\n'
    '\n'
    '**When to use:** When you need early access to new '
    'functionality and can tolerate potential breaking '
    'changes during updates.\n'
    '\n'
    '**💡 Legacy Exemptions:**\n'
    '\n'
    'Some packages don\'t follow the preview naming '
    'convention but are still considered preview status, as '
    'they were created before the preview phase was '
    'introduced:\n'
    '\n'
    '-   `@fluentui/theme`\n'
    '\n'
    '---\n'
    '\n'
    '### 🔵 Compat Packages\n'
    '\n'
    '**Characteristics:**\n'
    '\n'
    '-   Fluent UI v8 components adapted to use v9 '
    'dependencies and APIs\n'
    '-   Maintain familiar v8 APIs for easier migration\n'
    '-   Serve as bridge components during v8 to v9 '
    'transition\n'
    '-   May introduce breaking changes\n'
    '-   Version format: `0.x.x` (Note: translates to '
    '`0.major.(minor|patch)`)\n'
    '-   Not available from `@fluentui/react-components` '
    'suite\n'
    '-   Naming convention: `@fluentui/react-<name>-compat` '
    '(with `-compat` suffix)\n'
    '\n'
    '**Examples:** `@fluentui/react-datepicker-compat`, '
    '`@fluentui/react-calendar-compat`\n'
    '\n'
    '**Import path:** `@fluentui/react-<name>-compat`\n'
    '\n'
    '**When to use:** During migration from v8 to v9 when '
    'native v9 equivalents aren\'t available, or when you '
    'need time to gradually migrate complex implementations.\n'
    '\n'
    '**Migration strategy:** Plan to migrate to native v9 '
    'components as they become available and stable.\n'
    '\n'
    '---\n'
    '\n'
    '### 🔴 Deprecated Packages\n'
    '\n'
    '**Characteristics:**\n'
    '\n'
    '-   No longer supported or maintained\n'
    '-   Stable alternatives are typically available\n'
    '-   May not receive security updates or bug fixes\n'
    '-   Version format: varies (typically `9.0.0-alpha.x` or '
    '`9.0.0-beta.x`)\n'
    '-   Available from deprecated suite api '
    '`@fluentui/react-components/unstable`\n'
    '-   Naming convention: `@fluentui/react-<name>`\n'
    '\n'
    '**Examples:** `@fluentui/react-alert`, '
    '`@fluentui/react-infobutton`\n'
    '\n'
    '**Import path:** `@fluentui/react-components/unstable` '
    '(⚠️ **Note:** The `/unstable` API is deprecated)\n'
    '\n'
    '**When to use:** Not recommended for new development. '
    'Migrate to stable alternatives immediately.\n'
    '\n'
    '**Migration Guide:**\n'
    '\n'
    '| Deprecated Package | Stable Alternative |\n'
    '| --- | --- |\n'
    '| `@fluentui/react-alert` | `@fluentui/react-components` '
    '(`Toast`, `MessageBar`) |\n'
    '| `@fluentui/react-infobutton` | '
    '`@fluentui/react-components` (`InfoLabel`) |\n'
    '\n'
    '**Migration strategy:** Migrate to stable alternatives '
    'as soon as possible. Deprecated packages may not receive '
    'updates or security fixes.\n'
    '\n'
    '## Quick Reference\n'
    '\n'
    '| Maturity Level | Version Format | Production Ready | '
    'Breaking Changes | Import Source |\n'
    '| --- | --- | --- | --- | --- |\n'
    '| 🟢 Stable | `9.x.x` | ✅ Yes | ❌ No | '
    '`@fluentui/react-components` |\n'
    '| 🟡 Preview | `0.x.x` | ⚠️ Use with caution | ✅ Possible '
    '| `@fluentui/react--preview` |\n'
    '| 🔵 Compat | `0.x.x` | ⚠️ Migration only | ✅ Possible | '
    '`@fluentui/react--compat` |\n'
    '| 🔴 Deprecated | various | ❌ No | N/A | '
    '`@fluentui/react-components/unstable` |\n'
    '\n';
