// GENERATED BY tool/add_token_overrides.py — DO NOT EDIT BY HAND.

/// Identifies a single alias colour token.
///
/// The Dart counterpart of a key in Fluent React's flat `Theme` object.
/// Exists so a subtree can override one token without replacing the whole
/// palette — see `FluentThemeOverride`.
enum FluentColorToken {
  /// The `neutralForeground1` alias token.
  neutralForeground1,

  /// The `neutralForeground1Hover` alias token.
  neutralForeground1Hover,

  /// The `neutralForeground1Pressed` alias token.
  neutralForeground1Pressed,

  /// The `neutralForeground1Selected` alias token.
  neutralForeground1Selected,

  /// The `neutralForeground2` alias token.
  neutralForeground2,

  /// The `neutralForeground2Hover` alias token.
  neutralForeground2Hover,

  /// The `neutralForeground2Pressed` alias token.
  neutralForeground2Pressed,

  /// The `neutralForeground2Selected` alias token.
  neutralForeground2Selected,

  /// The `neutralForeground2BrandHover` alias token.
  neutralForeground2BrandHover,

  /// The `neutralForeground2BrandPressed` alias token.
  neutralForeground2BrandPressed,

  /// The `neutralForeground2BrandSelected` alias token.
  neutralForeground2BrandSelected,

  /// The `neutralForeground3` alias token.
  neutralForeground3,

  /// The `neutralForeground3Hover` alias token.
  neutralForeground3Hover,

  /// The `neutralForeground3Pressed` alias token.
  neutralForeground3Pressed,

  /// The `neutralForeground3Selected` alias token.
  neutralForeground3Selected,

  /// The `neutralForeground3BrandHover` alias token.
  neutralForeground3BrandHover,

  /// The `neutralForeground3BrandPressed` alias token.
  neutralForeground3BrandPressed,

  /// The `neutralForeground3BrandSelected` alias token.
  neutralForeground3BrandSelected,

  /// The `neutralForeground4` alias token.
  neutralForeground4,

  /// The `neutralForeground5` alias token.
  neutralForeground5,

  /// The `neutralForeground5Hover` alias token.
  neutralForeground5Hover,

  /// The `neutralForeground5Pressed` alias token.
  neutralForeground5Pressed,

  /// The `neutralForeground5Selected` alias token.
  neutralForeground5Selected,

  /// The `neutralForegroundDisabled` alias token.
  neutralForegroundDisabled,

  /// The `neutralForegroundInvertedDisabled` alias token.
  neutralForegroundInvertedDisabled,

  /// The `neutralForeground1Static` alias token.
  neutralForeground1Static,

  /// The `neutralForegroundStaticInverted` alias token.
  neutralForegroundStaticInverted,

  /// The `neutralForegroundInverted` alias token.
  neutralForegroundInverted,

  /// The `neutralForegroundInvertedHover` alias token.
  neutralForegroundInvertedHover,

  /// The `neutralForegroundInvertedPressed` alias token.
  neutralForegroundInvertedPressed,

  /// The `neutralForegroundInvertedSelected` alias token.
  neutralForegroundInvertedSelected,

  /// The `neutralForegroundInverted2` alias token.
  neutralForegroundInverted2,

  /// The `neutralForegroundOnBrand` alias token.
  neutralForegroundOnBrand,

  /// The `neutralForegroundInvertedLink` alias token.
  neutralForegroundInvertedLink,

  /// The `neutralForegroundInvertedLinkHover` alias token.
  neutralForegroundInvertedLinkHover,

  /// The `neutralForegroundInvertedLinkPressed` alias token.
  neutralForegroundInvertedLinkPressed,

  /// The `neutralForegroundInvertedLinkSelected` alias token.
  neutralForegroundInvertedLinkSelected,

  /// The `brandForegroundLink` alias token.
  brandForegroundLink,

  /// The `brandForegroundLinkHover` alias token.
  brandForegroundLinkHover,

  /// The `brandForegroundLinkPressed` alias token.
  brandForegroundLinkPressed,

  /// The `brandForegroundLinkSelected` alias token.
  brandForegroundLinkSelected,

  /// The `neutralForeground2Link` alias token.
  neutralForeground2Link,

  /// The `neutralForeground2LinkHover` alias token.
  neutralForeground2LinkHover,

  /// The `neutralForeground2LinkPressed` alias token.
  neutralForeground2LinkPressed,

  /// The `neutralForeground2LinkSelected` alias token.
  neutralForeground2LinkSelected,

  /// The `compoundBrandForeground1` alias token.
  compoundBrandForeground1,

  /// The `compoundBrandForeground1Hover` alias token.
  compoundBrandForeground1Hover,

  /// The `compoundBrandForeground1Pressed` alias token.
  compoundBrandForeground1Pressed,

  /// The `brandForeground1` alias token.
  brandForeground1,

  /// The `brandForeground2` alias token.
  brandForeground2,

  /// The `brandForeground2Hover` alias token.
  brandForeground2Hover,

  /// The `brandForeground2Pressed` alias token.
  brandForeground2Pressed,

  /// The `brandForegroundInverted` alias token.
  brandForegroundInverted,

  /// The `brandForegroundInvertedHover` alias token.
  brandForegroundInvertedHover,

  /// The `brandForegroundInvertedPressed` alias token.
  brandForegroundInvertedPressed,

  /// The `brandForegroundOnLight` alias token.
  brandForegroundOnLight,

  /// The `brandForegroundOnLightHover` alias token.
  brandForegroundOnLightHover,

  /// The `brandForegroundOnLightPressed` alias token.
  brandForegroundOnLightPressed,

  /// The `brandForegroundOnLightSelected` alias token.
  brandForegroundOnLightSelected,

  /// The `neutralBackground1` alias token.
  neutralBackground1,

  /// The `neutralBackground1Hover` alias token.
  neutralBackground1Hover,

  /// The `neutralBackground1Pressed` alias token.
  neutralBackground1Pressed,

  /// The `neutralBackground1Selected` alias token.
  neutralBackground1Selected,

  /// The `neutralBackground2` alias token.
  neutralBackground2,

  /// The `neutralBackground2Hover` alias token.
  neutralBackground2Hover,

  /// The `neutralBackground2Pressed` alias token.
  neutralBackground2Pressed,

  /// The `neutralBackground2Selected` alias token.
  neutralBackground2Selected,

  /// The `neutralBackground3` alias token.
  neutralBackground3,

  /// The `neutralBackground3Hover` alias token.
  neutralBackground3Hover,

  /// The `neutralBackground3Pressed` alias token.
  neutralBackground3Pressed,

  /// The `neutralBackground3Selected` alias token.
  neutralBackground3Selected,

  /// The `neutralBackground4` alias token.
  neutralBackground4,

  /// The `neutralBackground4Hover` alias token.
  neutralBackground4Hover,

  /// The `neutralBackground4Pressed` alias token.
  neutralBackground4Pressed,

  /// The `neutralBackground4Selected` alias token.
  neutralBackground4Selected,

  /// The `neutralBackground5` alias token.
  neutralBackground5,

  /// The `neutralBackground5Hover` alias token.
  neutralBackground5Hover,

  /// The `neutralBackground5Pressed` alias token.
  neutralBackground5Pressed,

  /// The `neutralBackground5Selected` alias token.
  neutralBackground5Selected,

  /// The `neutralBackground6` alias token.
  neutralBackground6,

  /// The `neutralBackground7` alias token.
  neutralBackground7,

  /// The `neutralBackground7Hover` alias token.
  neutralBackground7Hover,

  /// The `neutralBackground7Pressed` alias token.
  neutralBackground7Pressed,

  /// The `neutralBackground7Selected` alias token.
  neutralBackground7Selected,

  /// The `neutralBackground8` alias token.
  neutralBackground8,

  /// The `neutralBackgroundInverted` alias token.
  neutralBackgroundInverted,

  /// The `neutralBackgroundInvertedHover` alias token.
  neutralBackgroundInvertedHover,

  /// The `neutralBackgroundInvertedPressed` alias token.
  neutralBackgroundInvertedPressed,

  /// The `neutralBackgroundInvertedSelected` alias token.
  neutralBackgroundInvertedSelected,

  /// The `neutralBackgroundStatic` alias token.
  neutralBackgroundStatic,

  /// The `neutralBackgroundAlpha` alias token.
  neutralBackgroundAlpha,

  /// The `neutralBackgroundAlpha2` alias token.
  neutralBackgroundAlpha2,

  /// The `neutralBackgroundDisabled` alias token.
  neutralBackgroundDisabled,

  /// The `neutralBackgroundDisabled2` alias token.
  neutralBackgroundDisabled2,

  /// The `neutralBackgroundInvertedDisabled` alias token.
  neutralBackgroundInvertedDisabled,

  /// The `subtleBackground` alias token.
  subtleBackground,

  /// The `subtleBackgroundHover` alias token.
  subtleBackgroundHover,

  /// The `subtleBackgroundPressed` alias token.
  subtleBackgroundPressed,

  /// The `subtleBackgroundSelected` alias token.
  subtleBackgroundSelected,

  /// The `subtleBackgroundLightAlphaHover` alias token.
  subtleBackgroundLightAlphaHover,

  /// The `subtleBackgroundLightAlphaPressed` alias token.
  subtleBackgroundLightAlphaPressed,

  /// The `subtleBackgroundLightAlphaSelected` alias token.
  subtleBackgroundLightAlphaSelected,

  /// The `subtleBackgroundInverted` alias token.
  subtleBackgroundInverted,

  /// The `subtleBackgroundInvertedHover` alias token.
  subtleBackgroundInvertedHover,

  /// The `subtleBackgroundInvertedPressed` alias token.
  subtleBackgroundInvertedPressed,

  /// The `subtleBackgroundInvertedSelected` alias token.
  subtleBackgroundInvertedSelected,

  /// The `transparentBackground` alias token.
  transparentBackground,

  /// The `transparentBackgroundHover` alias token.
  transparentBackgroundHover,

  /// The `transparentBackgroundPressed` alias token.
  transparentBackgroundPressed,

  /// The `transparentBackgroundSelected` alias token.
  transparentBackgroundSelected,

  /// The `neutralStencil1` alias token.
  neutralStencil1,

  /// The `neutralStencil2` alias token.
  neutralStencil2,

  /// The `neutralStencil1Alpha` alias token.
  neutralStencil1Alpha,

  /// The `neutralStencil2Alpha` alias token.
  neutralStencil2Alpha,

  /// The `backgroundOverlay` alias token.
  backgroundOverlay,

  /// The `scrollbarOverlay` alias token.
  scrollbarOverlay,

  /// The `brandBackground` alias token.
  brandBackground,

  /// The `brandBackgroundHover` alias token.
  brandBackgroundHover,

  /// The `brandBackgroundPressed` alias token.
  brandBackgroundPressed,

  /// The `brandBackgroundSelected` alias token.
  brandBackgroundSelected,

  /// The `compoundBrandBackground` alias token.
  compoundBrandBackground,

  /// The `compoundBrandBackgroundHover` alias token.
  compoundBrandBackgroundHover,

  /// The `compoundBrandBackgroundPressed` alias token.
  compoundBrandBackgroundPressed,

  /// The `brandBackgroundStatic` alias token.
  brandBackgroundStatic,

  /// The `brandBackground2` alias token.
  brandBackground2,

  /// The `brandBackground2Hover` alias token.
  brandBackground2Hover,

  /// The `brandBackground2Pressed` alias token.
  brandBackground2Pressed,

  /// The `brandBackground3Static` alias token.
  brandBackground3Static,

  /// The `brandBackground4Static` alias token.
  brandBackground4Static,

  /// The `brandBackgroundInverted` alias token.
  brandBackgroundInverted,

  /// The `brandBackgroundInvertedHover` alias token.
  brandBackgroundInvertedHover,

  /// The `brandBackgroundInvertedPressed` alias token.
  brandBackgroundInvertedPressed,

  /// The `brandBackgroundInvertedSelected` alias token.
  brandBackgroundInvertedSelected,

  /// The `neutralCardBackground` alias token.
  neutralCardBackground,

  /// The `neutralCardBackgroundHover` alias token.
  neutralCardBackgroundHover,

  /// The `neutralCardBackgroundPressed` alias token.
  neutralCardBackgroundPressed,

  /// The `neutralCardBackgroundSelected` alias token.
  neutralCardBackgroundSelected,

  /// The `neutralCardBackgroundDisabled` alias token.
  neutralCardBackgroundDisabled,

  /// The `neutralStrokeAccessible` alias token.
  neutralStrokeAccessible,

  /// The `neutralStrokeAccessibleHover` alias token.
  neutralStrokeAccessibleHover,

  /// The `neutralStrokeAccessiblePressed` alias token.
  neutralStrokeAccessiblePressed,

  /// The `neutralStrokeAccessibleSelected` alias token.
  neutralStrokeAccessibleSelected,

  /// The `neutralStroke1` alias token.
  neutralStroke1,

  /// The `neutralStroke1Hover` alias token.
  neutralStroke1Hover,

  /// The `neutralStroke1Pressed` alias token.
  neutralStroke1Pressed,

  /// The `neutralStroke1Selected` alias token.
  neutralStroke1Selected,

  /// The `neutralStroke2` alias token.
  neutralStroke2,

  /// The `neutralStroke3` alias token.
  neutralStroke3,

  /// The `neutralStroke4` alias token.
  neutralStroke4,

  /// The `neutralStroke4Hover` alias token.
  neutralStroke4Hover,

  /// The `neutralStroke4Pressed` alias token.
  neutralStroke4Pressed,

  /// The `neutralStroke4Selected` alias token.
  neutralStroke4Selected,

  /// The `neutralStrokeSubtle` alias token.
  neutralStrokeSubtle,

  /// The `neutralStrokeOnBrand` alias token.
  neutralStrokeOnBrand,

  /// The `neutralStrokeOnBrand2` alias token.
  neutralStrokeOnBrand2,

  /// The `neutralStrokeOnBrand2Hover` alias token.
  neutralStrokeOnBrand2Hover,

  /// The `neutralStrokeOnBrand2Pressed` alias token.
  neutralStrokeOnBrand2Pressed,

  /// The `neutralStrokeOnBrand2Selected` alias token.
  neutralStrokeOnBrand2Selected,

  /// The `brandStroke1` alias token.
  brandStroke1,

  /// The `brandStroke2` alias token.
  brandStroke2,

  /// The `brandStroke2Hover` alias token.
  brandStroke2Hover,

  /// The `brandStroke2Pressed` alias token.
  brandStroke2Pressed,

  /// The `brandStroke2Contrast` alias token.
  brandStroke2Contrast,

  /// The `compoundBrandStroke` alias token.
  compoundBrandStroke,

  /// The `compoundBrandStrokeHover` alias token.
  compoundBrandStrokeHover,

  /// The `compoundBrandStrokePressed` alias token.
  compoundBrandStrokePressed,

  /// The `neutralStrokeDisabled` alias token.
  neutralStrokeDisabled,

  /// The `neutralStrokeDisabled2` alias token.
  neutralStrokeDisabled2,

  /// The `neutralStrokeInvertedDisabled` alias token.
  neutralStrokeInvertedDisabled,

  /// The `transparentStroke` alias token.
  transparentStroke,

  /// The `transparentStrokeInteractive` alias token.
  transparentStrokeInteractive,

  /// The `transparentStrokeDisabled` alias token.
  transparentStrokeDisabled,

  /// The `neutralStrokeAlpha` alias token.
  neutralStrokeAlpha,

  /// The `neutralStrokeAlpha2` alias token.
  neutralStrokeAlpha2,

  /// The `strokeFocus1` alias token.
  strokeFocus1,

  /// The `strokeFocus2` alias token.
  strokeFocus2,

  /// The `neutralShadowAmbient` alias token.
  neutralShadowAmbient,

  /// The `neutralShadowKey` alias token.
  neutralShadowKey,

  /// The `neutralShadowAmbientLighter` alias token.
  neutralShadowAmbientLighter,

  /// The `neutralShadowKeyLighter` alias token.
  neutralShadowKeyLighter,

  /// The `neutralShadowAmbientDarker` alias token.
  neutralShadowAmbientDarker,

  /// The `neutralShadowKeyDarker` alias token.
  neutralShadowKeyDarker,

  /// The `brandShadowAmbient` alias token.
  brandShadowAmbient,

  /// The `brandShadowKey` alias token.
  brandShadowKey,

  /// The `statusDangerBackground1` alias token.
  statusDangerBackground1,

  /// The `statusDangerBackground2` alias token.
  statusDangerBackground2,

  /// The `statusDangerBackground3` alias token.
  statusDangerBackground3,

  /// The `statusDangerBackground3Hover` alias token.
  statusDangerBackground3Hover,

  /// The `statusDangerBackground3Pressed` alias token.
  statusDangerBackground3Pressed,

  /// The `statusDangerForeground1` alias token.
  statusDangerForeground1,

  /// The `statusDangerForeground2` alias token.
  statusDangerForeground2,

  /// The `statusDangerForeground3` alias token.
  statusDangerForeground3,

  /// The `statusDangerForegroundInverted` alias token.
  statusDangerForegroundInverted,

  /// The `statusDangerBorderActive` alias token.
  statusDangerBorderActive,

  /// The `statusDangerBorder1` alias token.
  statusDangerBorder1,

  /// The `statusDangerBorder2` alias token.
  statusDangerBorder2,

  /// The `statusSuccessBackground1` alias token.
  statusSuccessBackground1,

  /// The `statusSuccessBackground2` alias token.
  statusSuccessBackground2,

  /// The `statusSuccessBackground3` alias token.
  statusSuccessBackground3,

  /// The `statusSuccessForeground1` alias token.
  statusSuccessForeground1,

  /// The `statusSuccessForeground2` alias token.
  statusSuccessForeground2,

  /// The `statusSuccessForeground3` alias token.
  statusSuccessForeground3,

  /// The `statusSuccessForegroundInverted` alias token.
  statusSuccessForegroundInverted,

  /// The `statusSuccessBorderActive` alias token.
  statusSuccessBorderActive,

  /// The `statusSuccessBorder1` alias token.
  statusSuccessBorder1,

  /// The `statusSuccessBorder2` alias token.
  statusSuccessBorder2,

  /// The `statusWarningBackground1` alias token.
  statusWarningBackground1,

  /// The `statusWarningBackground2` alias token.
  statusWarningBackground2,

  /// The `statusWarningBackground3` alias token.
  statusWarningBackground3,

  /// The `statusWarningForeground1` alias token.
  statusWarningForeground1,

  /// The `statusWarningForeground2` alias token.
  statusWarningForeground2,

  /// The `statusWarningForeground3` alias token.
  statusWarningForeground3,

  /// The `statusWarningForegroundInverted` alias token.
  statusWarningForegroundInverted,

  /// The `statusWarningBorderActive` alias token.
  statusWarningBorderActive,

  /// The `statusWarningBorder1` alias token.
  statusWarningBorder1,

  /// The `statusWarningBorder2` alias token.
  statusWarningBorder2,

  /// The `statusSevereBackground1` alias token.
  statusSevereBackground1,

  /// The `statusSevereBackground2` alias token.
  statusSevereBackground2,

  /// The `statusSevereBackground3` alias token.
  statusSevereBackground3,

  /// The `statusSevereForeground1` alias token.
  statusSevereForeground1,

  /// The `statusSevereForeground2` alias token.
  statusSevereForeground2,

  /// The `statusSevereForeground3` alias token.
  statusSevereForeground3,

  /// The `statusSevereForegroundInverted` alias token.
  statusSevereForegroundInverted,

  /// The `statusSevereBorder1` alias token.
  statusSevereBorder1,

  /// The `statusSevereBorder2` alias token.
  statusSevereBorder2,

  /// The `statusAvailableForeground3` alias token.
  statusAvailableForeground3,

  /// The `statusAwayBackground3` alias token.
  statusAwayBackground3,

  /// The `statusOofForeground3` alias token.
  statusOofForeground3,
}
