// GENERATED BY tool/generate_tokens.py — DO NOT EDIT BY HAND.
//
// Source: tool/figma_tokens.json, extracted from the official Microsoft
// "Fluent 2 Web (Community)" Figma file (key Heyk4N9SnwfIzupHlk3l7s) and
// resolved to literals by tool/merge_figma_tokens.py.
//
// To change a value, fix it upstream and re-run the generator.

import 'package:flutter/widgets.dart';

/// The Fluent 2 Acrylic material.
///
/// Acrylic is a translucent, blurred surface: a blurred backdrop with
/// a tint painted over it.
///
/// [backgroundBlur] is a **blur radius in logical pixels**, as Figma
/// and CSS `filter: blur()` express it — NOT a Gaussian sigma. Flutter's
/// `ImageFilter.blur` takes sigma, so halve it: `sigma = radius / 2`.
/// Passing the radius straight through doubles the blur.
///
/// Distinct from `FluentWindowsAcrylic` in `elevation.dart`, which is
/// WinUI's effect-graph recipe for the same visual effect.
@immutable
class FluentAcrylic {
  /// Creates the acrylic material for [brightness].
  const FluentAcrylic({this.brightness = Brightness.light});

  /// Which theme these tokens resolve for.
  final Brightness brightness;

  bool get _d => brightness == Brightness.dark;

  /// Figma `Material/Acrylic/Background/Blur`.
  double get backgroundBlur => 60.0;

  /// Figma `Material/Acrylic/Background/Primary`.
  Color get backgroundPrimary =>
      _d ? const Color(0xCC2E2E2E) : const Color(0x80FFFFFF);

  /// Figma `Material/Acrylic/Background/Secondary`.
  Color get backgroundSecondary =>
      _d ? const Color(0x9946406E) : const Color(0xB2E7ECF3);

  /// Figma `Material/Acrylic/Stroke/Stop 1`.
  Color get strokeStop1 =>
      _d ? const Color(0x33000000) : const Color(0x33FFFFFF);

  /// Figma `Material/Acrylic/Stroke/Stop 2`.
  Color get strokeStop2 =>
      _d ? const Color(0xFF2C3136) : const Color(0x33CFE4FA);

  /// Figma `Material/Acrylic/Stroke/Stop 3`.
  Color get strokeStop3 =>
      _d ? const Color(0x33000000) : const Color(0x33FFFFFF);
}
