// GENERATED BY tool/generate_tokens.py — DO NOT EDIT BY HAND.
//
// Source: tool/figma_tokens.json, extracted from the official Microsoft
// "Fluent 2 Web (Community)" Figma file (key Heyk4N9SnwfIzupHlk3l7s) and
// resolved to literals by tool/merge_figma_tokens.py.
//
// To change a value, fix it upstream and re-run the generator.

import 'package:flutter/widgets.dart';

/// A persona / accent colour family.
///
/// Source: Figma `Mode` collection, `Palette/*`. Upstream calls these
/// `colorPalette*`; they back avatars, presence, badges and tags.
enum FluentPaletteFamily {
  /// The `Anchor` palette family.
  anchor,

  /// The `Beige` palette family.
  beige,

  /// The `Berry` palette family.
  berry,

  /// The `Blue` palette family.
  blue,

  /// The `Brass` palette family.
  brass,

  /// The `Brown` palette family.
  brown,

  /// The `Cornflower` palette family.
  cornflower,

  /// The `Cranberry` palette family.
  cranberry,

  /// The `Dark green` palette family.
  darkGreen,

  /// The `Dark orange` palette family.
  darkOrange,

  /// The `Dark red` palette family.
  darkRed,

  /// The `Forest` palette family.
  forest,

  /// The `Gold` palette family.
  gold,

  /// The `Grape` palette family.
  grape,

  /// The `Green` palette family.
  green,

  /// The `Lavender` palette family.
  lavender,

  /// The `Light Green` palette family.
  lightGreen,

  /// The `Light teal` palette family.
  lightTeal,

  /// The `Lilac` palette family.
  lilac,

  /// The `Magenta` palette family.
  magenta,

  /// The `Marigold` palette family.
  marigold,

  /// The `Mink` palette family.
  mink,

  /// The `Navy` palette family.
  navy,

  /// The `Peach` palette family.
  peach,

  /// The `Pink` palette family.
  pink,

  /// The `Platinum` palette family.
  platinum,

  /// The `Plum` palette family.
  plum,

  /// The `Pumpkin` palette family.
  pumpkin,

  /// The `Purple` palette family.
  purple,

  /// The `Red` palette family.
  red,

  /// The `Royal blue` palette family.
  royalBlue,

  /// The `Seafoam` palette family.
  seafoam,

  /// The `Steel` palette family.
  steel,

  /// The `Teal` palette family.
  teal,

  /// The `Yellow` palette family.
  yellow,
}

/// The Fluent 2 palette colour layer.
///
/// Accessors marked as returning a nullable [Color] are not defined
/// for every family upstream — only the extended families carry the
/// full background/foreground/stroke set. Returning null rather than
/// inventing a value keeps the port honest.
@immutable
class FluentPaletteColors {
  /// Creates the palette layer for [brightness].
  const FluentPaletteColors({this.brightness = Brightness.light});

  /// Which theme these tokens resolve for.
  final Brightness brightness;

  bool get _d => brightness == Brightness.dark;

  /// Figma `Palette/<family>/Background/2/Rest`.
  Color background2Rest(FluentPaletteFamily family) =>
      (_d ? _background2RestDark : _background2RestLight)[family]!;

  static const Map<FluentPaletteFamily, Color> _background2RestLight = {
    FluentPaletteFamily.anchor: Color(0xFFBCC3C7),
    FluentPaletteFamily.beige: Color(0xFFD7D4D4),
    FluentPaletteFamily.berry: Color(0xFFEDBBE7),
    FluentPaletteFamily.blue: Color(0xFFA9D3F2),
    FluentPaletteFamily.brass: Color(0xFFE0CEA2),
    FluentPaletteFamily.brown: Color(0xFFDDC3B0),
    FluentPaletteFamily.cornflower: Color(0xFFC8D1FA),
    FluentPaletteFamily.cranberry: Color(0xFFEEACB2),
    FluentPaletteFamily.darkGreen: Color(0xFF9AD29A),
    FluentPaletteFamily.darkOrange: Color(0xFFF4BFAB),
    FluentPaletteFamily.darkRed: Color(0xFFD69CA5),
    FluentPaletteFamily.forest: Color(0xFFBDD99B),
    FluentPaletteFamily.gold: Color(0xFFECDFA5),
    FluentPaletteFamily.grape: Color(0xFFD9A7E0),
    FluentPaletteFamily.green: Color(0xFF9FD89F),
    FluentPaletteFamily.lavender: Color(0xFFA3B2E8),
    FluentPaletteFamily.lightGreen: Color(0xFFA7E3A5),
    FluentPaletteFamily.lightTeal: Color(0xFFA6E9ED),
    FluentPaletteFamily.lilac: Color(0xFFE6BFED),
    FluentPaletteFamily.magenta: Color(0xFFECA5D1),
    FluentPaletteFamily.marigold: Color(0xFFF9E2AE),
    FluentPaletteFamily.mink: Color(0xFFCECCCB),
    FluentPaletteFamily.navy: Color(0xFFA3B2E8),
    FluentPaletteFamily.peach: Color(0xFFFFDDB3),
    FluentPaletteFamily.pink: Color(0xFFF7C0E3),
    FluentPaletteFamily.platinum: Color(0xFFCDD6D8),
    FluentPaletteFamily.plum: Color(0xFFD696C0),
    FluentPaletteFamily.pumpkin: Color(0xFFEFC4AD),
    FluentPaletteFamily.purple: Color(0xFFC6B1DE),
    FluentPaletteFamily.red: Color(0xFFF1BBBC),
    FluentPaletteFamily.royalBlue: Color(0xFF9ABFDC),
    FluentPaletteFamily.seafoam: Color(0xFFA8F0CD),
    FluentPaletteFamily.steel: Color(0xFF94C8D4),
    FluentPaletteFamily.teal: Color(0xFF9BD9DB),
    FluentPaletteFamily.yellow: Color(0xFFFEF7B2),
  };

  static const Map<FluentPaletteFamily, Color> _background2RestDark = {
    FluentPaletteFamily.anchor: Color(0xFF202427),
    FluentPaletteFamily.beige: Color(0xFF444241),
    FluentPaletteFamily.berry: Color(0xFF6D2064),
    FluentPaletteFamily.blue: Color(0xFF004377),
    FluentPaletteFamily.brass: Color(0xFF553E06),
    FluentPaletteFamily.brown: Color(0xFF50301A),
    FluentPaletteFamily.cornflower: Color(0xFF2C3C85),
    FluentPaletteFamily.cranberry: Color(0xFF6E0811),
    FluentPaletteFamily.darkGreen: Color(0xFF063B06),
    FluentPaletteFamily.darkOrange: Color(0xFF7A2101),
    FluentPaletteFamily.darkRed: Color(0xFF590815),
    FluentPaletteFamily.forest: Color(0xFF294903),
    FluentPaletteFamily.gold: Color(0xFF6C5700),
    FluentPaletteFamily.grape: Color(0xFF4C0D55),
    FluentPaletteFamily.green: Color(0xFF094509),
    FluentPaletteFamily.lavender: Color(0xFF3F3682),
    FluentPaletteFamily.lightGreen: Color(0xFF0B5A08),
    FluentPaletteFamily.lightTeal: Color(0xFF00666D),
    FluentPaletteFamily.lilac: Color(0xFF63276D),
    FluentPaletteFamily.magenta: Color(0xFF6B0043),
    FluentPaletteFamily.marigold: Color(0xFF835B00),
    FluentPaletteFamily.mink: Color(0xFF343231),
    FluentPaletteFamily.navy: Color(0xFF001665),
    FluentPaletteFamily.peach: Color(0xFF8F4E00),
    FluentPaletteFamily.pink: Color(0xFF80215D),
    FluentPaletteFamily.platinum: Color(0xFF3B4447),
    FluentPaletteFamily.plum: Color(0xFF5A003B),
    FluentPaletteFamily.pumpkin: Color(0xFF712D09),
    FluentPaletteFamily.purple: Color(0xFF341A51),
    FluentPaletteFamily.red: Color(0xFF751D1F),
    FluentPaletteFamily.royalBlue: Color(0xFF002C4E),
    FluentPaletteFamily.seafoam: Color(0xFF00723B),
    FluentPaletteFamily.steel: Color(0xFF00333F),
    FluentPaletteFamily.teal: Color(0xFF02494C),
    FluentPaletteFamily.yellow: Color(0xFF817400),
  };

  /// Figma `Palette/<family>/Foreground/2/Rest`.
  Color foreground2Rest(FluentPaletteFamily family) =>
      (_d ? _foreground2RestDark : _foreground2RestLight)[family]!;

  static const Map<FluentPaletteFamily, Color> _foreground2RestLight = {
    FluentPaletteFamily.anchor: Color(0xFF202427),
    FluentPaletteFamily.beige: Color(0xFF444241),
    FluentPaletteFamily.berry: Color(0xFF6D2064),
    FluentPaletteFamily.blue: Color(0xFF004377),
    FluentPaletteFamily.brass: Color(0xFF553E06),
    FluentPaletteFamily.brown: Color(0xFF50301A),
    FluentPaletteFamily.cornflower: Color(0xFF2C3C85),
    FluentPaletteFamily.cranberry: Color(0xFF6E0811),
    FluentPaletteFamily.darkGreen: Color(0xFF063B06),
    FluentPaletteFamily.darkOrange: Color(0xFF7A2101),
    FluentPaletteFamily.darkRed: Color(0xFF420610),
    FluentPaletteFamily.forest: Color(0xFF294903),
    FluentPaletteFamily.gold: Color(0xFF6C5700),
    FluentPaletteFamily.grape: Color(0xFF4C0D55),
    FluentPaletteFamily.green: Color(0xFF094509),
    FluentPaletteFamily.lavender: Color(0xFF3F3682),
    FluentPaletteFamily.lightGreen: Color(0xFF0B5A08),
    FluentPaletteFamily.lightTeal: Color(0xFF00666D),
    FluentPaletteFamily.lilac: Color(0xFF63276D),
    FluentPaletteFamily.magenta: Color(0xFF6B0043),
    FluentPaletteFamily.marigold: Color(0xFF835B00),
    FluentPaletteFamily.mink: Color(0xFF343231),
    FluentPaletteFamily.navy: Color(0xFF001665),
    FluentPaletteFamily.peach: Color(0xFF8F4E00),
    FluentPaletteFamily.pink: Color(0xFF80215D),
    FluentPaletteFamily.platinum: Color(0xFF3B4447),
    FluentPaletteFamily.plum: Color(0xFF43002B),
    FluentPaletteFamily.pumpkin: Color(0xFF712D09),
    FluentPaletteFamily.purple: Color(0xFF341A51),
    FluentPaletteFamily.red: Color(0xFF751D1F),
    FluentPaletteFamily.royalBlue: Color(0xFF002C4E),
    FluentPaletteFamily.seafoam: Color(0xFF00723B),
    FluentPaletteFamily.steel: Color(0xFF00333F),
    FluentPaletteFamily.teal: Color(0xFF02494C),
    FluentPaletteFamily.yellow: Color(0xFF817400),
  };

  static const Map<FluentPaletteFamily, Color> _foreground2RestDark = {
    FluentPaletteFamily.anchor: Color(0xFFBCC3C7),
    FluentPaletteFamily.beige: Color(0xFFD7D4D4),
    FluentPaletteFamily.berry: Color(0xFFEDBBE7),
    FluentPaletteFamily.blue: Color(0xFFA9D3F2),
    FluentPaletteFamily.brass: Color(0xFFE0CEA2),
    FluentPaletteFamily.brown: Color(0xFFDDC3B0),
    FluentPaletteFamily.cornflower: Color(0xFFC8D1FA),
    FluentPaletteFamily.cranberry: Color(0xFFEEACB2),
    FluentPaletteFamily.darkGreen: Color(0xFF9AD29A),
    FluentPaletteFamily.darkOrange: Color(0xFFF4BFAB),
    FluentPaletteFamily.darkRed: Color(0xFFD69CA5),
    FluentPaletteFamily.forest: Color(0xFFBDD99B),
    FluentPaletteFamily.gold: Color(0xFFECDFA5),
    FluentPaletteFamily.grape: Color(0xFFD9A7E0),
    FluentPaletteFamily.green: Color(0xFF9FD89F),
    FluentPaletteFamily.lavender: Color(0xFFD2CCF8),
    FluentPaletteFamily.lightGreen: Color(0xFFA7E3A5),
    FluentPaletteFamily.lightTeal: Color(0xFFA6E9ED),
    FluentPaletteFamily.lilac: Color(0xFFE6BFED),
    FluentPaletteFamily.magenta: Color(0xFFECA5D1),
    FluentPaletteFamily.marigold: Color(0xFFF9E2AE),
    FluentPaletteFamily.mink: Color(0xFFCECCCB),
    FluentPaletteFamily.navy: Color(0xFFA3B2E8),
    FluentPaletteFamily.peach: Color(0xFFFFDDB3),
    FluentPaletteFamily.pink: Color(0xFFF7C0E3),
    FluentPaletteFamily.platinum: Color(0xFFCDD6D8),
    FluentPaletteFamily.plum: Color(0xFFD696C0),
    FluentPaletteFamily.pumpkin: Color(0xFFEFC4AD),
    FluentPaletteFamily.purple: Color(0xFFC6B1DE),
    FluentPaletteFamily.red: Color(0xFFEEACB2),
    FluentPaletteFamily.royalBlue: Color(0xFF9ABFDC),
    FluentPaletteFamily.seafoam: Color(0xFFA8F0CD),
    FluentPaletteFamily.steel: Color(0xFF94C8D4),
    FluentPaletteFamily.teal: Color(0xFF9BD9DB),
    FluentPaletteFamily.yellow: Color(0xFFFEF7B2),
  };

  /// Figma `Palette/<family>/Stroke/Active/Rest`.
  Color strokeActiveRest(FluentPaletteFamily family) =>
      (_d ? _strokeActiveRestDark : _strokeActiveRestLight)[family]!;

  static const Map<FluentPaletteFamily, Color> _strokeActiveRestLight = {
    FluentPaletteFamily.anchor: Color(0xFF394146),
    FluentPaletteFamily.beige: Color(0xFF7A7574),
    FluentPaletteFamily.berry: Color(0xFFC239B3),
    FluentPaletteFamily.blue: Color(0xFF0078D4),
    FluentPaletteFamily.brass: Color(0xFF986F0B),
    FluentPaletteFamily.brown: Color(0xFF8E562E),
    FluentPaletteFamily.cornflower: Color(0xFF4F6BED),
    FluentPaletteFamily.cranberry: Color(0xFFC50F1F),
    FluentPaletteFamily.darkGreen: Color(0xFF0B6A0B),
    FluentPaletteFamily.darkOrange: Color(0xFFDA3B01),
    FluentPaletteFamily.darkRed: Color(0xFF750B1C),
    FluentPaletteFamily.forest: Color(0xFF498205),
    FluentPaletteFamily.gold: Color(0xFFC19C00),
    FluentPaletteFamily.grape: Color(0xFF881798),
    FluentPaletteFamily.green: Color(0xFF107C10),
    FluentPaletteFamily.lavender: Color(0xFF7160E8),
    FluentPaletteFamily.lightGreen: Color(0xFF13A10E),
    FluentPaletteFamily.lightTeal: Color(0xFF00B7C3),
    FluentPaletteFamily.lilac: Color(0xFFB146C2),
    FluentPaletteFamily.magenta: Color(0xFFBF0077),
    FluentPaletteFamily.marigold: Color(0xFFEAA300),
    FluentPaletteFamily.mink: Color(0xFF5D5A58),
    FluentPaletteFamily.navy: Color(0xFF0027B4),
    FluentPaletteFamily.peach: Color(0xFFFF8C00),
    FluentPaletteFamily.pink: Color(0xFFE43BA6),
    FluentPaletteFamily.platinum: Color(0xFF69797E),
    FluentPaletteFamily.plum: Color(0xFFBF0077),
    FluentPaletteFamily.pumpkin: Color(0xFFCA5010),
    FluentPaletteFamily.purple: Color(0xFF5C2E91),
    FluentPaletteFamily.red: Color(0xFFD13438),
    FluentPaletteFamily.royalBlue: Color(0xFF004E8C),
    FluentPaletteFamily.seafoam: Color(0xFF00CC6A),
    FluentPaletteFamily.steel: Color(0xFF005B70),
    FluentPaletteFamily.teal: Color(0xFF038387),
    FluentPaletteFamily.yellow: Color(0xFFFDE300),
  };

  static const Map<FluentPaletteFamily, Color> _strokeActiveRestDark = {
    FluentPaletteFamily.anchor: Color(0xFF808A90),
    FluentPaletteFamily.beige: Color(0xFFAFABAA),
    FluentPaletteFamily.berry: Color(0xFFDA7ED0),
    FluentPaletteFamily.blue: Color(0xFF5CAAE5),
    FluentPaletteFamily.brass: Color(0xFFC1A256),
    FluentPaletteFamily.brown: Color(0xFFBB8F6F),
    FluentPaletteFamily.cornflower: Color(0xFF93A4F4),
    FluentPaletteFamily.cranberry: Color(0xFFDC626D),
    FluentPaletteFamily.darkGreen: Color(0xFF4DA64D),
    FluentPaletteFamily.darkOrange: Color(0xFFE9835E),
    FluentPaletteFamily.darkRed: Color(0xFF962F3F),
    FluentPaletteFamily.forest: Color(0xFF85B44C),
    FluentPaletteFamily.gold: Color(0xFFDAC157),
    FluentPaletteFamily.grape: Color(0xFFB55FC1),
    FluentPaletteFamily.green: Color(0xFF54B054),
    FluentPaletteFamily.lavender: Color(0xFFA79CF1),
    FluentPaletteFamily.lightGreen: Color(0xFF5EC75A),
    FluentPaletteFamily.lightTeal: Color(0xFF58D3DB),
    FluentPaletteFamily.lilac: Color(0xFFCF87DA),
    FluentPaletteFamily.magenta: Color(0xFFD957A8),
    FluentPaletteFamily.marigold: Color(0xFFF2C661),
    FluentPaletteFamily.mink: Color(0xFF9E9B99),
    FluentPaletteFamily.navy: Color(0xFF546FD2),
    FluentPaletteFamily.peach: Color(0xFFFFBA66),
    FluentPaletteFamily.pink: Color(0xFFEF85C8),
    FluentPaletteFamily.platinum: Color(0xFFA0ADB2),
    FluentPaletteFamily.plum: Color(0xFFD957A8),
    FluentPaletteFamily.pumpkin: Color(0xFFDF8E64),
    FluentPaletteFamily.purple: Color(0xFF9470BD),
    FluentPaletteFamily.red: Color(0xFFE37D80),
    FluentPaletteFamily.royalBlue: Color(0xFF4A89BA),
    FluentPaletteFamily.seafoam: Color(0xFF5AE0A0),
    FluentPaletteFamily.steel: Color(0xFF4496A9),
    FluentPaletteFamily.teal: Color(0xFF4CB4B7),
    FluentPaletteFamily.yellow: Color(0xFFFEEE66),
  };

  /// Figma `Palette/<family>/Background/1/Rest`.
  Color? background1Rest(FluentPaletteFamily family) =>
      (_d ? _background1RestDark : _background1RestLight)[family];

  static const Map<FluentPaletteFamily, Color> _background1RestLight = {
    FluentPaletteFamily.berry: Color(0xFFFDF5FC),
    FluentPaletteFamily.darkOrange: Color(0xFFFDF6F3),
    FluentPaletteFamily.green: Color(0xFFF1FAF1),
    FluentPaletteFamily.lightGreen: Color(0xFFF2FBF2),
    FluentPaletteFamily.marigold: Color(0xFFFEFBF4),
    FluentPaletteFamily.red: Color(0xFFFDF6F6),
    FluentPaletteFamily.yellow: Color(0xFFFFFEF5),
  };

  static const Map<FluentPaletteFamily, Color> _background1RestDark = {
    FluentPaletteFamily.berry: Color(0xFF3A1136),
    FluentPaletteFamily.darkOrange: Color(0xFF411200),
    FluentPaletteFamily.green: Color(0xFF052505),
    FluentPaletteFamily.lightGreen: Color(0xFF063004),
    FluentPaletteFamily.marigold: Color(0xFF463100),
    FluentPaletteFamily.red: Color(0xFF3F1011),
    FluentPaletteFamily.yellow: Color(0xFF4C4400),
  };

  /// Figma `Palette/<family>/Background/3/Rest`.
  Color? background3Rest(FluentPaletteFamily family) =>
      (_d ? _background3RestDark : _background3RestLight)[family];

  static const Map<FluentPaletteFamily, Color> _background3RestLight = {
    FluentPaletteFamily.berry: Color(0xFFC239B3),
    FluentPaletteFamily.darkOrange: Color(0xFFDA3B01),
    FluentPaletteFamily.green: Color(0xFF107C10),
    FluentPaletteFamily.lightGreen: Color(0xFF13A10E),
    FluentPaletteFamily.marigold: Color(0xFFEAA300),
    FluentPaletteFamily.red: Color(0xFFD13438),
    FluentPaletteFamily.yellow: Color(0xFFFDE300),
  };

  static const Map<FluentPaletteFamily, Color> _background3RestDark = {
    FluentPaletteFamily.berry: Color(0xFFC239B3),
    FluentPaletteFamily.darkOrange: Color(0xFFDA3B01),
    FluentPaletteFamily.green: Color(0xFF107C10),
    FluentPaletteFamily.lightGreen: Color(0xFF13A10E),
    FluentPaletteFamily.marigold: Color(0xFFEAA300),
    FluentPaletteFamily.red: Color(0xFF750B1C),
    FluentPaletteFamily.yellow: Color(0xFFFDE300),
  };

  /// Figma `Palette/<family>/Foreground/1/Rest`.
  Color? foreground1Rest(FluentPaletteFamily family) =>
      (_d ? _foreground1RestDark : _foreground1RestLight)[family];

  static const Map<FluentPaletteFamily, Color> _foreground1RestLight = {
    FluentPaletteFamily.berry: Color(0xFFAF33A1),
    FluentPaletteFamily.darkOrange: Color(0xFFC43501),
    FluentPaletteFamily.green: Color(0xFF0E700E),
    FluentPaletteFamily.lightGreen: Color(0xFF11910D),
    FluentPaletteFamily.marigold: Color(0xFFD39300),
    FluentPaletteFamily.red: Color(0xFFBC2F32),
    FluentPaletteFamily.yellow: Color(0xFF817400),
  };

  static const Map<FluentPaletteFamily, Color> _foreground1RestDark = {
    FluentPaletteFamily.berry: Color(0xFFDA7ED0),
    FluentPaletteFamily.darkOrange: Color(0xFFE9835E),
    FluentPaletteFamily.green: Color(0xFF54B054),
    FluentPaletteFamily.lightGreen: Color(0xFF5EC75A),
    FluentPaletteFamily.marigold: Color(0xFFF2C661),
    FluentPaletteFamily.red: Color(0xFFE37D80),
    FluentPaletteFamily.yellow: Color(0xFFFEEE66),
  };

  /// Figma `Palette/<family>/Foreground/1/Rest 2`.
  Color? foreground1Rest2(FluentPaletteFamily family) =>
      (_d ? _foreground1Rest2Dark : _foreground1Rest2Light)[family];

  static const Map<FluentPaletteFamily, Color> _foreground1Rest2Light = {
    FluentPaletteFamily.marigold: Color(0xFFEAA300),
  };

  static const Map<FluentPaletteFamily, Color> _foreground1Rest2Dark = {
    FluentPaletteFamily.marigold: Color(0xFFEFB839),
  };

  /// Figma `Palette/<family>/Foreground/3/Rest`.
  Color? foreground3Rest(FluentPaletteFamily family) =>
      (_d ? _foreground3RestDark : _foreground3RestLight)[family];

  static const Map<FluentPaletteFamily, Color> _foreground3RestLight = {
    FluentPaletteFamily.berry: Color(0xFFC239B3),
    FluentPaletteFamily.darkOrange: Color(0xFFDA3B01),
    FluentPaletteFamily.green: Color(0xFF107C10),
    FluentPaletteFamily.lightGreen: Color(0xFF13A10E),
    FluentPaletteFamily.marigold: Color(0xFFEAA300),
    FluentPaletteFamily.red: Color(0xFFD13438),
    FluentPaletteFamily.yellow: Color(0xFFFDE300),
  };

  static const Map<FluentPaletteFamily, Color> _foreground3RestDark = {
    FluentPaletteFamily.berry: Color(0xFFD161C4),
    FluentPaletteFamily.darkOrange: Color(0xFFE9835E),
    FluentPaletteFamily.green: Color(0xFF54B054),
    FluentPaletteFamily.lightGreen: Color(0xFF3DB838),
    FluentPaletteFamily.marigold: Color(0xFFEFB839),
    FluentPaletteFamily.red: Color(0xFFE37D80),
    FluentPaletteFamily.yellow: Color(0xFFFDEA3D),
  };

  /// Figma `Palette/<family>/Foreground/Inverted/Rest`.
  Color? foregroundInvertedRest(FluentPaletteFamily family) =>
      (_d ? _foregroundInvertedRestDark : _foregroundInvertedRestLight)[family];

  static const Map<FluentPaletteFamily, Color> _foregroundInvertedRestLight = {
    FluentPaletteFamily.green: Color(0xFF359B35),
    FluentPaletteFamily.red: Color(0xFFDC5E62),
    FluentPaletteFamily.yellow: Color(0xFFFEF7B2),
  };

  static const Map<FluentPaletteFamily, Color> _foregroundInvertedRestDark = {
    FluentPaletteFamily.green: Color(0xFF107C10),
    FluentPaletteFamily.red: Color(0xFFD13438),
    FluentPaletteFamily.yellow: Color(0xFF817400),
  };

  /// Figma `Palette/<family>/Stroke/1/Rest`.
  Color? stroke1Rest(FluentPaletteFamily family) =>
      (_d ? _stroke1RestDark : _stroke1RestLight)[family];

  static const Map<FluentPaletteFamily, Color> _stroke1RestLight = {
    FluentPaletteFamily.berry: Color(0xFFEDBBE7),
    FluentPaletteFamily.darkOrange: Color(0xFFF4BFAB),
    FluentPaletteFamily.green: Color(0xFF9FD89F),
    FluentPaletteFamily.lightGreen: Color(0xFFA7E3A5),
    FluentPaletteFamily.marigold: Color(0xFFF9E2AE),
    FluentPaletteFamily.red: Color(0xFFF1BBBC),
    FluentPaletteFamily.yellow: Color(0xFFFEF7B2),
  };

  static const Map<FluentPaletteFamily, Color> _stroke1RestDark = {
    FluentPaletteFamily.berry: Color(0xFFC239B3),
    FluentPaletteFamily.darkOrange: Color(0xFFDA3B01),
    FluentPaletteFamily.green: Color(0xFF107C10),
    FluentPaletteFamily.lightGreen: Color(0xFF13A10E),
    FluentPaletteFamily.marigold: Color(0xFFEAA300),
    FluentPaletteFamily.red: Color(0xFFD13438),
    FluentPaletteFamily.yellow: Color(0xFFFDE300),
  };

  /// Figma `Palette/<family>/Stroke/2/Rest`.
  Color? stroke2Rest(FluentPaletteFamily family) =>
      (_d ? _stroke2RestDark : _stroke2RestLight)[family];

  static const Map<FluentPaletteFamily, Color> _stroke2RestLight = {
    FluentPaletteFamily.berry: Color(0xFFC239B3),
    FluentPaletteFamily.darkOrange: Color(0xFFDA3B01),
    FluentPaletteFamily.green: Color(0xFF107C10),
    FluentPaletteFamily.lightGreen: Color(0xFF13A10E),
    FluentPaletteFamily.marigold: Color(0xFFEAA300),
    FluentPaletteFamily.red: Color(0xFFD13438),
    FluentPaletteFamily.yellow: Color(0xFFFDE300),
  };

  static const Map<FluentPaletteFamily, Color> _stroke2RestDark = {
    FluentPaletteFamily.berry: Color(0xFFD161C4),
    FluentPaletteFamily.darkOrange: Color(0xFFE9835E),
    FluentPaletteFamily.green: Color(0xFF54B054),
    FluentPaletteFamily.lightGreen: Color(0xFF3DB838),
    FluentPaletteFamily.marigold: Color(0xFFEFB839),
    FluentPaletteFamily.red: Color(0xFFE37D80),
    FluentPaletteFamily.yellow: Color(0xFFFDEA3D),
  };
}
