// GENERATED BY tool/generate_tokens.py — DO NOT EDIT BY HAND.
//
// Source: tool/figma_tokens.json, extracted from the official Microsoft
// "Fluent 2 Web (Community)" Figma file (key Heyk4N9SnwfIzupHlk3l7s) and
// resolved to literals by tool/merge_figma_tokens.py.
//
// To change a value, fix it upstream and re-run the generator.

import 'package:flutter/widgets.dart';

/// A family in the Fluent 2 shared colour ramp.
///
/// These are the raw ramps the persona, presence and accent tokens
/// alias into. Source: Figma ` Global` collection, `Colors/Shared/*`.
enum FluentSharedColor {
  /// The `Anchor` shared ramp.
  anchor,

  /// The `Beige` shared ramp.
  beige,

  /// The `Berry` shared ramp.
  berry,

  /// The `Blue` shared ramp.
  blue,

  /// The `Brass` shared ramp.
  brass,

  /// The `Bronze` shared ramp.
  bronze,

  /// The `Brown` shared ramp.
  brown,

  /// The `Burgundy` shared ramp.
  burgundy,

  /// The `Charcoal` shared ramp.
  charcoal,

  /// The `Cornflower` shared ramp.
  cornflower,

  /// The `Cranberry` shared ramp.
  cranberry,

  /// The `Cyan` shared ramp.
  cyan,

  /// The `Dark blue` shared ramp.
  darkBlue,

  /// The `Dark brown` shared ramp.
  darkBrown,

  /// The `Dark green` shared ramp.
  darkGreen,

  /// The `Dark orange` shared ramp.
  darkOrange,

  /// The `Dark purple` shared ramp.
  darkPurple,

  /// The `Dark red` shared ramp.
  darkRed,

  /// The `Dark teal` shared ramp.
  darkTeal,

  /// The `Forest` shared ramp.
  forest,

  /// The `Gold` shared ramp.
  gold,

  /// The `Grape` shared ramp.
  grape,

  /// The `Green` shared ramp.
  green,

  /// The `Hot pink` shared ramp.
  hotPink,

  /// The `Lavender` shared ramp.
  lavender,

  /// The `Light blue` shared ramp.
  lightBlue,

  /// The `Light green` shared ramp.
  lightGreen,

  /// The `Light teal` shared ramp.
  lightTeal,

  /// The `Lilac` shared ramp.
  lilac,

  /// The `Lime` shared ramp.
  lime,

  /// The `Magenta` shared ramp.
  magenta,

  /// The `Marigold` shared ramp.
  marigold,

  /// The `Mink` shared ramp.
  mink,

  /// The `Navy` shared ramp.
  navy,

  /// The `Orange` shared ramp.
  orange,

  /// The `Orchid` shared ramp.
  orchid,

  /// The `Peach` shared ramp.
  peach,

  /// The `Pink` shared ramp.
  pink,

  /// The `Platinum` shared ramp.
  platinum,

  /// The `Plum` shared ramp.
  plum,

  /// The `Pumpkin` shared ramp.
  pumpkin,

  /// The `Purple` shared ramp.
  purple,

  /// The `Red` shared ramp.
  red,

  /// The `Royal blue` shared ramp.
  royalBlue,

  /// The `Seafoam` shared ramp.
  seafoam,

  /// The `Silver` shared ramp.
  silver,

  /// The `Steel` shared ramp.
  steel,

  /// The `Teal` shared ramp.
  teal,

  /// The `Yellow` shared ramp.
  yellow,
}

/// The twelve stops of one shared colour ramp.
@immutable
class FluentSharedShades {
  /// Creates a ramp from its twelve stops.
  const FluentSharedShades({
    required this.shade50,
    required this.shade40,
    required this.shade30,
    required this.shade20,
    required this.shade10,
    required this.primary,
    required this.tint10,
    required this.tint20,
    required this.tint30,
    required this.tint40,
    required this.tint50,
    required this.tint60,
  });

  /// The `Shade 50` stop.
  final Color shade50;

  /// The `Shade 40` stop.
  final Color shade40;

  /// The `Shade 30` stop.
  final Color shade30;

  /// The `Shade 20` stop.
  final Color shade20;

  /// The `Shade 10` stop.
  final Color shade10;

  /// The `Primary` stop.
  final Color primary;

  /// The `Tint 10` stop.
  final Color tint10;

  /// The `Tint 20` stop.
  final Color tint20;

  /// The `Tint 30` stop.
  final Color tint30;

  /// The `Tint 40` stop.
  final Color tint40;

  /// The `Tint 50` stop.
  final Color tint50;

  /// The `Tint 60` stop.
  final Color tint60;
}

/// The 49 shared colour ramps, keyed by family.
abstract final class FluentSharedRamp {
  /// Every shared ramp, keyed by [FluentSharedColor].
  static const Map<FluentSharedColor, FluentSharedShades> all = {
    FluentSharedColor.anchor: FluentSharedShades(
      shade50: Color(0xFF090A0B),
      shade40: Color(0xFF111315),
      shade30: Color(0xFF202427),
      shade20: Color(0xFF2B3135),
      shade10: Color(0xFF333A3F),
      primary: Color(0xFF394146),
      tint10: Color(0xFF4D565C),
      tint20: Color(0xFF626C72),
      tint30: Color(0xFF808A90),
      tint40: Color(0xFFBCC3C7),
      tint50: Color(0xFFDBDFE1),
      tint60: Color(0xFFF6F7F8),
    ),
    FluentSharedColor.beige: FluentSharedShades(
      shade50: Color(0xFF141313),
      shade40: Color(0xFF252323),
      shade30: Color(0xFF444241),
      shade20: Color(0xFF5D5958),
      shade10: Color(0xFF6E6968),
      primary: Color(0xFF7A7574),
      tint10: Color(0xFF8A8584),
      tint20: Color(0xFF9A9594),
      tint30: Color(0xFFAFABAA),
      tint40: Color(0xFFD7D4D4),
      tint50: Color(0xFFEAE8E8),
      tint60: Color(0xFFFAF9F9),
    ),
    FluentSharedColor.berry: FluentSharedShades(
      shade50: Color(0xFF1F091D),
      shade40: Color(0xFF3A1136),
      shade30: Color(0xFF6D2064),
      shade20: Color(0xFF932B88),
      shade10: Color(0xFFAF33A1),
      primary: Color(0xFFC239B3),
      tint10: Color(0xFFC94CBC),
      tint20: Color(0xFFD161C4),
      tint30: Color(0xFFDA7ED0),
      tint40: Color(0xFFEDBBE7),
      tint50: Color(0xFFF5DAF2),
      tint60: Color(0xFFFDF5FC),
    ),
    FluentSharedColor.blue: FluentSharedShades(
      shade50: Color(0xFF001322),
      shade40: Color(0xFF002440),
      shade30: Color(0xFF004377),
      shade20: Color(0xFF005BA1),
      shade10: Color(0xFF006CBF),
      primary: Color(0xFF0078D4),
      tint10: Color(0xFF1A86D9),
      tint20: Color(0xFF3595DE),
      tint30: Color(0xFF5CAAE5),
      tint40: Color(0xFFA9D3F2),
      tint50: Color(0xFFD0E7F8),
      tint60: Color(0xFFF3F9FD),
    ),
    FluentSharedColor.brass: FluentSharedShades(
      shade50: Color(0xFF181202),
      shade40: Color(0xFF2E2103),
      shade30: Color(0xFF553E06),
      shade20: Color(0xFF745408),
      shade10: Color(0xFF89640A),
      primary: Color(0xFF986F0B),
      tint10: Color(0xFFA47D1E),
      tint20: Color(0xFFB18C34),
      tint30: Color(0xFFC1A256),
      tint40: Color(0xFFE0CEA2),
      tint50: Color(0xFFEFE4CB),
      tint60: Color(0xFFFBF8F2),
    ),
    FluentSharedColor.bronze: FluentSharedShades(
      shade50: Color(0xFF1B0A01),
      shade40: Color(0xFF321303),
      shade30: Color(0xFF5E2405),
      shade20: Color(0xFF7F3107),
      shade10: Color(0xFF963A08),
      primary: Color(0xFFA74109),
      tint10: Color(0xFFB2521E),
      tint20: Color(0xFFBC6535),
      tint30: Color(0xFFCA8057),
      tint40: Color(0xFFE5BBA4),
      tint50: Color(0xFFF1D9CC),
      tint60: Color(0xFFFBF5F2),
    ),
    FluentSharedColor.brown: FluentSharedShades(
      shade50: Color(0xFF170E07),
      shade40: Color(0xFF2B1A0E),
      shade30: Color(0xFF50301A),
      shade20: Color(0xFF6C4123),
      shade10: Color(0xFF804D29),
      primary: Color(0xFF8E562E),
      tint10: Color(0xFF9C663F),
      tint20: Color(0xFFA97652),
      tint30: Color(0xFFBB8F6F),
      tint40: Color(0xFFDDC3B0),
      tint50: Color(0xFFEDDED3),
      tint60: Color(0xFFFAF7F4),
    ),
    FluentSharedColor.burgundy: FluentSharedShades(
      shade50: Color(0xFF1A0607),
      shade40: Color(0xFF310B0D),
      shade30: Color(0xFF5C1519),
      shade20: Color(0xFF7D1D21),
      shade10: Color(0xFF942228),
      primary: Color(0xFFA4262C),
      tint10: Color(0xFFAF393E),
      tint20: Color(0xFFBA4D52),
      tint30: Color(0xFFC86C70),
      tint40: Color(0xFFE4AFB2),
      tint50: Color(0xFFF0D3D4),
      tint60: Color(0xFFFBF4F4),
    ),
    FluentSharedColor.charcoal: FluentSharedShades(
      shade50: Color(0xFF090909),
      shade40: Color(0xFF111111),
      shade30: Color(0xFF202020),
      shade20: Color(0xFF2B2B2B),
      shade10: Color(0xFF333333),
      primary: Color(0xFF393939),
      tint10: Color(0xFF515151),
      tint20: Color(0xFF686868),
      tint30: Color(0xFF888888),
      tint40: Color(0xFFC4C4C4),
      tint50: Color(0xFFDFDFDF),
      tint60: Color(0xFFF7F7F7),
    ),
    FluentSharedColor.cornflower: FluentSharedShades(
      shade50: Color(0xFF0D1126),
      shade40: Color(0xFF182047),
      shade30: Color(0xFF2C3C85),
      shade20: Color(0xFF3C51B4),
      shade10: Color(0xFF4760D5),
      primary: Color(0xFF4F6BED),
      tint10: Color(0xFF637CEF),
      tint20: Color(0xFF778DF1),
      tint30: Color(0xFF93A4F4),
      tint40: Color(0xFFC8D1FA),
      tint50: Color(0xFFE1E6FC),
      tint60: Color(0xFFF7F9FE),
    ),
    FluentSharedColor.cranberry: FluentSharedShades(
      shade50: Color(0xFF200205),
      shade40: Color(0xFF3B0509),
      shade30: Color(0xFF6E0811),
      shade20: Color(0xFF960B18),
      shade10: Color(0xFFB10E1C),
      primary: Color(0xFFC50F1F),
      tint10: Color(0xFFCC2635),
      tint20: Color(0xFFD33F4C),
      tint30: Color(0xFFDC626D),
      tint40: Color(0xFFEEACB2),
      tint50: Color(0xFFF6D1D5),
      tint60: Color(0xFFFDF3F4),
    ),
    FluentSharedColor.cyan: FluentSharedShades(
      shade50: Color(0xFF00181E),
      shade40: Color(0xFF002E38),
      shade30: Color(0xFF005669),
      shade20: Color(0xFF00748F),
      shade10: Color(0xFF008AA9),
      primary: Color(0xFF0099BC),
      tint10: Color(0xFF18A4C4),
      tint20: Color(0xFF31AFCC),
      tint30: Color(0xFF56BFD7),
      tint40: Color(0xFFA4DEEB),
      tint50: Color(0xFFCDEDF4),
      tint60: Color(0xFFF2FAFC),
    ),
    FluentSharedColor.darkBlue: FluentSharedShades(
      shade50: Color(0xFF000910),
      shade40: Color(0xFF00111F),
      shade30: Color(0xFF002039),
      shade20: Color(0xFF002B4E),
      shade10: Color(0xFF00335C),
      primary: Color(0xFF003966),
      tint10: Color(0xFF0E4A78),
      tint20: Color(0xFF215C8B),
      tint30: Color(0xFF4178A3),
      tint40: Color(0xFF92B5D1),
      tint50: Color(0xFFC2D6E7),
      tint60: Color(0xFFEFF4F9),
    ),
    FluentSharedColor.darkBrown: FluentSharedShades(
      shade50: Color(0xFF0C0704),
      shade40: Color(0xFF170C08),
      shade30: Color(0xFF2B1710),
      shade20: Color(0xFF3A1F15),
      shade10: Color(0xFF452519),
      primary: Color(0xFF4D291C),
      tint10: Color(0xFF623A2B),
      tint20: Color(0xFF784D3E),
      tint30: Color(0xFF946B5C),
      tint40: Color(0xFFCAADA3),
      tint50: Color(0xFFE3D2CB),
      tint60: Color(0xFFF8F3F2),
    ),
    FluentSharedColor.darkGreen: FluentSharedShades(
      shade50: Color(0xFF021102),
      shade40: Color(0xFF032003),
      shade30: Color(0xFF063B06),
      shade20: Color(0xFF085108),
      shade10: Color(0xFF0A5F0A),
      primary: Color(0xFF0B6A0B),
      tint10: Color(0xFF1A7C1A),
      tint20: Color(0xFF2D8E2D),
      tint30: Color(0xFF4DA64D),
      tint40: Color(0xFF9AD29A),
      tint50: Color(0xFFC6E7C6),
      tint60: Color(0xFFF0F9F0),
    ),
    FluentSharedColor.darkOrange: FluentSharedShades(
      shade50: Color(0xFF230900),
      shade40: Color(0xFF411200),
      shade30: Color(0xFF7A2101),
      shade20: Color(0xFFA62D01),
      shade10: Color(0xFFC43501),
      primary: Color(0xFFDA3B01),
      tint10: Color(0xFFDE501C),
      tint20: Color(0xFFE36537),
      tint30: Color(0xFFE9835E),
      tint40: Color(0xFFF4BFAB),
      tint50: Color(0xFFF9DCD1),
      tint60: Color(0xFFFDF6F3),
    ),
    FluentSharedColor.darkPurple: FluentSharedShades(
      shade50: Color(0xFF0A0411),
      shade40: Color(0xFF130820),
      shade30: Color(0xFF240F3C),
      shade20: Color(0xFF311552),
      shade10: Color(0xFF3A1861),
      primary: Color(0xFF401B6C),
      tint10: Color(0xFF512B7E),
      tint20: Color(0xFF633E8F),
      tint30: Color(0xFF7E5CA7),
      tint40: Color(0xFFB9A3D3),
      tint50: Color(0xFFD8CCE7),
      tint60: Color(0xFFF5F2F9),
    ),
    FluentSharedColor.darkRed: FluentSharedShades(
      shade50: Color(0xFF130204),
      shade40: Color(0xFF230308),
      shade30: Color(0xFF420610),
      shade20: Color(0xFF590815),
      shade10: Color(0xFF690A19),
      primary: Color(0xFF750B1C),
      tint10: Color(0xFF861B2C),
      tint20: Color(0xFF962F3F),
      tint30: Color(0xFFAC4F5E),
      tint40: Color(0xFFD69CA5),
      tint50: Color(0xFFE9C7CD),
      tint60: Color(0xFFF9F0F2),
    ),
    FluentSharedColor.darkTeal: FluentSharedShades(
      shade50: Color(0xFF001010),
      shade40: Color(0xFF001F1F),
      shade30: Color(0xFF003939),
      shade20: Color(0xFF004E4E),
      shade10: Color(0xFF005C5C),
      primary: Color(0xFF006666),
      tint10: Color(0xFF0E7878),
      tint20: Color(0xFF218B8B),
      tint30: Color(0xFF41A3A3),
      tint40: Color(0xFF92D1D1),
      tint50: Color(0xFFC2E7E7),
      tint60: Color(0xFFEFF9F9),
    ),
    FluentSharedColor.forest: FluentSharedShades(
      shade50: Color(0xFF0C1501),
      shade40: Color(0xFF162702),
      shade30: Color(0xFF294903),
      shade20: Color(0xFF376304),
      shade10: Color(0xFF427505),
      primary: Color(0xFF498205),
      tint10: Color(0xFF599116),
      tint20: Color(0xFF6BA02B),
      tint30: Color(0xFF85B44C),
      tint40: Color(0xFFBDD99B),
      tint50: Color(0xFFDBEBC7),
      tint60: Color(0xFFF6FAF0),
    ),
    FluentSharedColor.gold: FluentSharedShades(
      shade50: Color(0xFF1F1900),
      shade40: Color(0xFF3A2F00),
      shade30: Color(0xFF6C5700),
      shade20: Color(0xFF937700),
      shade10: Color(0xFFAE8C00),
      primary: Color(0xFFC19C00),
      tint10: Color(0xFFC8A718),
      tint20: Color(0xFFD0B232),
      tint30: Color(0xFFDAC157),
      tint40: Color(0xFFECDFA5),
      tint50: Color(0xFFF5EECE),
      tint60: Color(0xFFFDFBF2),
    ),
    FluentSharedColor.grape: FluentSharedShades(
      shade50: Color(0xFF160418),
      shade40: Color(0xFF29072E),
      shade30: Color(0xFF4C0D55),
      shade20: Color(0xFF671174),
      shade10: Color(0xFF7A1589),
      primary: Color(0xFF881798),
      tint10: Color(0xFF952AA4),
      tint20: Color(0xFFA33FB1),
      tint30: Color(0xFFB55FC1),
      tint40: Color(0xFFD9A7E0),
      tint50: Color(0xFFEACEEF),
      tint60: Color(0xFFFAF2FB),
    ),
    FluentSharedColor.green: FluentSharedShades(
      shade50: Color(0xFF031403),
      shade40: Color(0xFF052505),
      shade30: Color(0xFF094509),
      shade20: Color(0xFF0C5E0C),
      shade10: Color(0xFF0E700E),
      primary: Color(0xFF107C10),
      tint10: Color(0xFF218C21),
      tint20: Color(0xFF359B35),
      tint30: Color(0xFF54B054),
      tint40: Color(0xFF9FD89F),
      tint50: Color(0xFFC9EAC9),
      tint60: Color(0xFFF1FAF1),
    ),
    FluentSharedColor.hotPink: FluentSharedShades(
      shade50: Color(0xFF240016),
      shade40: Color(0xFF44002A),
      shade30: Color(0xFF7F004E),
      shade20: Color(0xFFAD006A),
      shade10: Color(0xFFCC007E),
      primary: Color(0xFFE3008C),
      tint10: Color(0xFFE61C99),
      tint20: Color(0xFFEA38A6),
      tint30: Color(0xFFEE5FB7),
      tint40: Color(0xFFF7ADDA),
      tint50: Color(0xFFFBD2EB),
      tint60: Color(0xFFFEF4FA),
    ),
    FluentSharedColor.lavender: FluentSharedShades(
      shade50: Color(0xFF120F25),
      shade40: Color(0xFF221D46),
      shade30: Color(0xFF3F3682),
      shade20: Color(0xFF5649B0),
      shade10: Color(0xFF6656D1),
      primary: Color(0xFF7160E8),
      tint10: Color(0xFF8172EB),
      tint20: Color(0xFF9184EE),
      tint30: Color(0xFFA79CF1),
      tint40: Color(0xFFD2CCF8),
      tint50: Color(0xFFE7E4FB),
      tint60: Color(0xFFF9F8FE),
    ),
    FluentSharedColor.lightBlue: FluentSharedShades(
      shade50: Color(0xFF091823),
      shade40: Color(0xFF112D42),
      shade30: Color(0xFF20547C),
      shade20: Color(0xFF2C72A8),
      shade10: Color(0xFF3487C7),
      primary: Color(0xFF3A96DD),
      tint10: Color(0xFF4FA1E1),
      tint20: Color(0xFF65ADE5),
      tint30: Color(0xFF83BDEB),
      tint40: Color(0xFFBFDDF5),
      tint50: Color(0xFFDCEDFA),
      tint60: Color(0xFFF6FAFE),
    ),
    FluentSharedColor.lightGreen: FluentSharedShades(
      shade50: Color(0xFF031A02),
      shade40: Color(0xFF063004),
      shade30: Color(0xFF0B5A08),
      shade20: Color(0xFF0E7A0B),
      shade10: Color(0xFF11910D),
      primary: Color(0xFF13A10E),
      tint10: Color(0xFF27AC22),
      tint20: Color(0xFF3DB838),
      tint30: Color(0xFF5EC75A),
      tint40: Color(0xFFA7E3A5),
      tint50: Color(0xFFCEF0CD),
      tint60: Color(0xFFF2FBF2),
    ),
    FluentSharedColor.lightTeal: FluentSharedShades(
      shade50: Color(0xFF001D1F),
      shade40: Color(0xFF00373A),
      shade30: Color(0xFF00666D),
      shade20: Color(0xFF008B94),
      shade10: Color(0xFF00A5AF),
      primary: Color(0xFF00B7C3),
      tint10: Color(0xFF18BFCA),
      tint20: Color(0xFF32C8D1),
      tint30: Color(0xFF58D3DB),
      tint40: Color(0xFFA6E9ED),
      tint50: Color(0xFFCEF3F5),
      tint60: Color(0xFFF2FCFD),
    ),
    FluentSharedColor.lilac: FluentSharedShades(
      shade50: Color(0xFF1C0B1F),
      shade40: Color(0xFF35153A),
      shade30: Color(0xFF63276D),
      shade20: Color(0xFF863593),
      shade10: Color(0xFF9F3FAF),
      primary: Color(0xFFB146C2),
      tint10: Color(0xFFBA58C9),
      tint20: Color(0xFFC36BD1),
      tint30: Color(0xFFCF87DA),
      tint40: Color(0xFFE6BFED),
      tint50: Color(0xFFF2DCF5),
      tint60: Color(0xFFFCF6FD),
    ),
    FluentSharedColor.lime: FluentSharedShades(
      shade50: Color(0xFF121B06),
      shade40: Color(0xFF23330B),
      shade30: Color(0xFF405F14),
      shade20: Color(0xFF57811B),
      shade10: Color(0xFF689920),
      primary: Color(0xFF73AA24),
      tint10: Color(0xFF81B437),
      tint20: Color(0xFF90BE4C),
      tint30: Color(0xFFA4CC6C),
      tint40: Color(0xFFCFE5AF),
      tint50: Color(0xFFE5F1D3),
      tint60: Color(0xFFF8FCF4),
    ),
    FluentSharedColor.magenta: FluentSharedShades(
      shade50: Color(0xFF1F0013),
      shade40: Color(0xFF390024),
      shade30: Color(0xFF6B0043),
      shade20: Color(0xFF91005A),
      shade10: Color(0xFFAC006B),
      primary: Color(0xFFBF0077),
      tint10: Color(0xFFC71885),
      tint20: Color(0xFFCE3293),
      tint30: Color(0xFFD957A8),
      tint40: Color(0xFFECA5D1),
      tint50: Color(0xFFF5CEE6),
      tint60: Color(0xFFFCF2F9),
    ),
    FluentSharedColor.marigold: FluentSharedShades(
      shade50: Color(0xFF251A00),
      shade40: Color(0xFF463100),
      shade30: Color(0xFF835B00),
      shade20: Color(0xFFB27C00),
      shade10: Color(0xFFD39300),
      primary: Color(0xFFEAA300),
      tint10: Color(0xFFEDAD1C),
      tint20: Color(0xFFEFB839),
      tint30: Color(0xFFF2C661),
      tint40: Color(0xFFF9E2AE),
      tint50: Color(0xFFFCEFD3),
      tint60: Color(0xFFFEFBF4),
    ),
    FluentSharedColor.mink: FluentSharedShades(
      shade50: Color(0xFF0F0E0E),
      shade40: Color(0xFF1C1B1A),
      shade30: Color(0xFF343231),
      shade20: Color(0xFF474443),
      shade10: Color(0xFF54514F),
      primary: Color(0xFF5D5A58),
      tint10: Color(0xFF706D6B),
      tint20: Color(0xFF84817E),
      tint30: Color(0xFF9E9B99),
      tint40: Color(0xFFCECCCB),
      tint50: Color(0xFFE5E4E3),
      tint60: Color(0xFFF8F8F8),
    ),
    FluentSharedColor.navy: FluentSharedShades(
      shade50: Color(0xFF00061D),
      shade40: Color(0xFF000C36),
      shade30: Color(0xFF001665),
      shade20: Color(0xFF001E89),
      shade10: Color(0xFF0023A2),
      primary: Color(0xFF0027B4),
      tint10: Color(0xFF173BBD),
      tint20: Color(0xFF3050C6),
      tint30: Color(0xFF546FD2),
      tint40: Color(0xFFA3B2E8),
      tint50: Color(0xFFCCD5F3),
      tint60: Color(0xFFF2F4FC),
    ),
    FluentSharedColor.orange: FluentSharedShades(
      shade50: Color(0xFF271002),
      shade40: Color(0xFF4A1E04),
      shade30: Color(0xFF8A3707),
      shade20: Color(0xFFBC4B09),
      shade10: Color(0xFFDE590B),
      primary: Color(0xFFF7630C),
      tint10: Color(0xFFF87528),
      tint20: Color(0xFFF98845),
      tint30: Color(0xFFFAA06B),
      tint40: Color(0xFFFDCFB4),
      tint50: Color(0xFFFEE5D7),
      tint60: Color(0xFFFFF9F5),
    ),
    FluentSharedColor.orchid: FluentSharedShades(
      shade50: Color(0xFF16101D),
      shade40: Color(0xFF281E37),
      shade30: Color(0xFF4C3867),
      shade20: Color(0xFF674C8C),
      shade10: Color(0xFF795AA6),
      primary: Color(0xFF8764B8),
      tint10: Color(0xFF9373C0),
      tint20: Color(0xFFA083C9),
      tint30: Color(0xFFB29AD4),
      tint40: Color(0xFFD7CAEA),
      tint50: Color(0xFFE9E2F4),
      tint60: Color(0xFFF9F8FC),
    ),
    FluentSharedColor.peach: FluentSharedShades(
      shade50: Color(0xFF291600),
      shade40: Color(0xFF4D2A00),
      shade30: Color(0xFF8F4E00),
      shade20: Color(0xFFC26A00),
      shade10: Color(0xFFE67E00),
      primary: Color(0xFFFF8C00),
      tint10: Color(0xFFFF9A1F),
      tint20: Color(0xFFFFA83D),
      tint30: Color(0xFFFFBA66),
      tint40: Color(0xFFFFDDB3),
      tint50: Color(0xFFFFEDD6),
      tint60: Color(0xFFFFFAF5),
    ),
    FluentSharedColor.pink: FluentSharedShades(
      shade50: Color(0xFF24091B),
      shade40: Color(0xFF441232),
      shade30: Color(0xFF80215D),
      shade20: Color(0xFFAD2D7E),
      shade10: Color(0xFFCD3595),
      primary: Color(0xFFE43BA6),
      tint10: Color(0xFFE750B0),
      tint20: Color(0xFFEA66BA),
      tint30: Color(0xFFEF85C8),
      tint40: Color(0xFFF7C0E3),
      tint50: Color(0xFFFBDDF0),
      tint60: Color(0xFFFEF6FB),
    ),
    FluentSharedColor.platinum: FluentSharedShades(
      shade50: Color(0xFF111314),
      shade40: Color(0xFF1F2426),
      shade30: Color(0xFF3B4447),
      shade20: Color(0xFF505C60),
      shade10: Color(0xFF5F6D71),
      primary: Color(0xFF69797E),
      tint10: Color(0xFF79898D),
      tint20: Color(0xFF89989D),
      tint30: Color(0xFFA0ADB2),
      tint40: Color(0xFFCDD6D8),
      tint50: Color(0xFFE4E9EA),
      tint60: Color(0xFFF8F9FA),
    ),
    FluentSharedColor.plum: FluentSharedShades(
      shade50: Color(0xFF13000C),
      shade40: Color(0xFF240017),
      shade30: Color(0xFF43002B),
      shade20: Color(0xFF5A003B),
      shade10: Color(0xFF6B0045),
      primary: Color(0xFF77004D),
      tint10: Color(0xFF87105D),
      tint20: Color(0xFF98246F),
      tint30: Color(0xFFAD4589),
      tint40: Color(0xFFD696C0),
      tint50: Color(0xFFE9C4DC),
      tint60: Color(0xFFFAF0F6),
    ),
    FluentSharedColor.pumpkin: FluentSharedShades(
      shade50: Color(0xFF200D03),
      shade40: Color(0xFF3D1805),
      shade30: Color(0xFF712D09),
      shade20: Color(0xFF9A3D0C),
      shade10: Color(0xFFB6480E),
      primary: Color(0xFFCA5010),
      tint10: Color(0xFFD06228),
      tint20: Color(0xFFD77440),
      tint30: Color(0xFFDF8E64),
      tint40: Color(0xFFEFC4AD),
      tint50: Color(0xFFF7DFD2),
      tint60: Color(0xFFFDF7F4),
    ),
    FluentSharedColor.purple: FluentSharedShades(
      shade50: Color(0xFF0F0717),
      shade40: Color(0xFF1C0E2B),
      shade30: Color(0xFF341A51),
      shade20: Color(0xFF46236E),
      shade10: Color(0xFF532982),
      primary: Color(0xFF5C2E91),
      tint10: Color(0xFF6B3F9E),
      tint20: Color(0xFF7C52AB),
      tint30: Color(0xFF9470BD),
      tint40: Color(0xFFC6B1DE),
      tint50: Color(0xFFE0D3ED),
      tint60: Color(0xFFF7F4FB),
    ),
    FluentSharedColor.red: FluentSharedShades(
      shade50: Color(0xFF210809),
      shade40: Color(0xFF3F1011),
      shade30: Color(0xFF751D1F),
      shade20: Color(0xFF9F282B),
      shade10: Color(0xFFBC2F32),
      primary: Color(0xFFD13438),
      tint10: Color(0xFFD7494C),
      tint20: Color(0xFFDC5E62),
      tint30: Color(0xFFE37D80),
      tint40: Color(0xFFF1BBBC),
      tint50: Color(0xFFF8DADB),
      tint60: Color(0xFFFDF6F6),
    ),
    FluentSharedColor.royalBlue: FluentSharedShades(
      shade50: Color(0xFF000C16),
      shade40: Color(0xFF00172A),
      shade30: Color(0xFF002C4E),
      shade20: Color(0xFF003B6A),
      shade10: Color(0xFF00467E),
      primary: Color(0xFF004E8C),
      tint10: Color(0xFF125E9A),
      tint20: Color(0xFF286FA8),
      tint30: Color(0xFF4A89BA),
      tint40: Color(0xFF9ABFDC),
      tint50: Color(0xFFC7DCED),
      tint60: Color(0xFFF0F6FA),
    ),
    FluentSharedColor.seafoam: FluentSharedShades(
      shade50: Color(0xFF002111),
      shade40: Color(0xFF003D20),
      shade30: Color(0xFF00723B),
      shade20: Color(0xFF009B51),
      shade10: Color(0xFF00B85F),
      primary: Color(0xFF00CC6A),
      tint10: Color(0xFF19D279),
      tint20: Color(0xFF34D889),
      tint30: Color(0xFF5AE0A0),
      tint40: Color(0xFFA8F0CD),
      tint50: Color(0xFFCFF7E4),
      tint60: Color(0xFFF3FDF8),
    ),
    FluentSharedColor.silver: FluentSharedShades(
      shade50: Color(0xFF151818),
      shade40: Color(0xFF282D2E),
      shade30: Color(0xFF4A5356),
      shade20: Color(0xFF657174),
      shade10: Color(0xFF78868A),
      primary: Color(0xFF859599),
      tint10: Color(0xFF92A1A5),
      tint20: Color(0xFFA0AEB1),
      tint30: Color(0xFFB3BFC2),
      tint40: Color(0xFFD8DFE0),
      tint50: Color(0xFFEAEEEF),
      tint60: Color(0xFFFAFBFB),
    ),
    FluentSharedColor.steel: FluentSharedShades(
      shade50: Color(0xFF000F12),
      shade40: Color(0xFF001B22),
      shade30: Color(0xFF00333F),
      shade20: Color(0xFF004555),
      shade10: Color(0xFF005265),
      primary: Color(0xFF005B70),
      tint10: Color(0xFF0F6C81),
      tint20: Color(0xFF237D92),
      tint30: Color(0xFF4496A9),
      tint40: Color(0xFF94C8D4),
      tint50: Color(0xFFC3E1E8),
      tint60: Color(0xFFEFF7F9),
    ),
    FluentSharedColor.teal: FluentSharedShades(
      shade50: Color(0xFF001516),
      shade40: Color(0xFF012728),
      shade30: Color(0xFF02494C),
      shade20: Color(0xFF026467),
      shade10: Color(0xFF037679),
      primary: Color(0xFF038387),
      tint10: Color(0xFF159195),
      tint20: Color(0xFF2AA0A4),
      tint30: Color(0xFF4CB4B7),
      tint40: Color(0xFF9BD9DB),
      tint50: Color(0xFFC7EBEC),
      tint60: Color(0xFFF0FAFA),
    ),
    FluentSharedColor.yellow: FluentSharedShades(
      shade50: Color(0xFF282400),
      shade40: Color(0xFF4C4400),
      shade30: Color(0xFF817400),
      shade20: Color(0xFFC0AD00),
      shade10: Color(0xFFE4CC00),
      primary: Color(0xFFFDE300),
      tint10: Color(0xFFFDE61E),
      tint20: Color(0xFFFDEA3D),
      tint30: Color(0xFFFEEE66),
      tint40: Color(0xFFFEF7B2),
      tint50: Color(0xFFFFFAD6),
      tint60: Color(0xFFFFFEF5),
    ),
  };

  /// The ramp for [family]. Never null — every family is present.
  static FluentSharedShades of(FluentSharedColor family) => all[family]!;
}
