name: fluent_2_fonts_web
description: "Web-only open-source Selawik font assets for Fluent 2."
version: 0.0.2
repository: https://github.com/B1Digital/fluent_ui_2_flutter
issue_tracker: https://github.com/B1Digital/fluent_ui_2_flutter/issues
resolution: workspace

screenshots:
  - description: "The Fluent 2 for Flutter project logo."
    path: screenshots/fluent_2_flutter.png

environment:
  sdk: ^3.12.2
  flutter: ">=3.41.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - path: lib/fonts/selawk.ttf
      platforms:
        - web
    - path: lib/fonts/selawksb.ttf
      platforms:
        - web
    - path: lib/fonts/selawkb.ttf
      platforms:
        - web
