/// Asserts a widget against the numbers extracted from the official Fluent
/// Figma file.
///
/// ## Why not golden images
///
/// The implementation uses Selawik as an open-source Segoe UI substitute, and
/// Skia's antialiasing does not match Figma's renderer, so a pixel diff would be
/// permanently flaky — every component would ship with a stale golden and a
/// `// TODO: regenerate`. This harness instead compares **resolved numbers**:
/// size, padding, radius, stroke width, ARGB fills, and text metrics. Text is
/// compared as font size and line height only, never as a rendered glyph box,
/// so the label string in a test is irrelevant.
///
/// ## Using it
///
/// ```dart
/// final spec = loadSpec('button');
/// final variant = spec.variant(const {
///   'Style': 'Primary', 'State': 'Rest',
///   'Size': 'Medium', 'Layout': 'Icon and label',
/// });
///
/// testWidgets(variant.name, (tester) async {
///   await tester.pumpWidget(/* ... */);
///   expectSpec(tester, find.byType(FluentButton), variant);
/// });
/// ```
///
/// Fixtures are generated by `tool/extract_component_spec.py`; the shape is
/// documented in `test/fixtures/README.md`.
library;

import 'dart:convert';
import 'dart:io';

import 'package:flutter/widgets.dart';
import 'package:flutter_test/flutter_test.dart';

/// Reads `test/fixtures/<component>.json`.
///
/// The path is resolved by walking up from [Directory.current] until a
/// directory containing it is found, so this works whether `flutter test` was
/// started from the package root or from a subdirectory of it.
SpecFixture loadSpec(String component) {
  final relative = 'test/fixtures/$component.json';
  var directory = Directory.current;
  while (true) {
    final file = File('${directory.path}/$relative');
    if (file.existsSync()) {
      final decoded = jsonDecode(file.readAsStringSync());
      return SpecFixture._(_obj(decoded));
    }
    final parent = directory.parent;
    // Reaching the filesystem root leaves parent == directory.
    if (parent.path == directory.path) break;
    directory = parent;
  }
  throw StateError(
    'No $relative found in ${Directory.current.path} or any ancestor. '
    'Generate it with tool/extract_component_spec.py — see '
    'test/fixtures/README.md.',
  );
}

/// Every variant of one Figma component set.
class SpecFixture {
  SpecFixture._(Map<String, dynamic> json)
    : component = _str(json['component']),
      properties = {
        for (final entry in _obj(json['properties']).entries)
          entry.key: [for (final value in _list(entry.value)) _str(value)],
      },
      variants = [
        for (final row in _list(json['variants'])) SpecVariant._(_obj(row)),
      ];

  /// Fixture name, matching the file name — `button` for `button.json`.
  final String component;

  /// Every variant property and the values it accepts, in Figma's own order and
  /// with the ` (Default)` marker already stripped.
  final Map<String, List<String>> properties;

  /// Every variant, sorted by [SpecVariant.name].
  final List<SpecVariant> variants;

  /// The single variant matching [props], which need not name every property
  /// so long as the match is unambiguous.
  ///
  /// Throws rather than guessing when nothing matches or several do — with 150
  /// variants in one set, silently taking the first would mean a component
  /// passing against a spec nobody chose.
  SpecVariant variant(Map<String, String> props) {
    final matches = where(props);
    if (matches.length == 1) return matches.single;

    final query = props.entries.map((e) => '${e.key}=${e.value}').join(', ');
    if (matches.isEmpty) {
      final unknown = props.entries
          .where((e) => properties[e.key]?.contains(e.value) != true)
          .map(
            (e) => properties.containsKey(e.key)
                ? '${e.key}=${e.value} (${e.key} accepts: '
                      '${properties[e.key]!.join(', ')})'
                : '${e.key} is not a property of $component '
                      '(has: ${properties.keys.join(', ')})',
          );
      throw StateError(
        '$component has no variant matching {$query}. '
        '${unknown.isEmpty ? '' : unknown.join('; ')}',
      );
    }

    final missing = properties.keys.where((k) => !props.containsKey(k));
    throw StateError(
      '{$query} matches ${matches.length} variants of $component. '
      'Add ${missing.join(', ')} to narrow it.',
    );
  }

  /// Every variant matching [props]. Properties absent from [props] are free.
  List<SpecVariant> where(Map<String, String> props) => variants
      .where((v) => props.entries.every((e) => v.props[e.key] == e.value))
      .toList();
}

/// One resolved variant: the numbers a component must reproduce, plus the
/// tokens it must reach for to get them.
class SpecVariant {
  SpecVariant._(Map<String, dynamic> json)
    : name = _str(json['name']),
      figmaName = _str(json['figmaName']),
      nodeId = _str(json['nodeId']),
      props = {
        for (final entry in _obj(json['props']).entries)
          entry.key: _str(entry.value),
      },
      size = Size(
        _dbl(_obj(json['size'])['width']),
        _dbl(_obj(json['size'])['height']),
      ),
      padding = json['padding'] == null
          ? null
          : EdgeInsets.only(
              top: _dbl(_obj(json['padding'])['top']),
              right: _dbl(_obj(json['padding'])['right']),
              bottom: _dbl(_obj(json['padding'])['bottom']),
              left: _dbl(_obj(json['padding'])['left']),
            ),
      gap = json['gap'] == null ? null : _dbl(json['gap']),
      radius = _radius(json['radius']),
      strokeWidth = _uniformStroke(json['strokeWidth']),
      strokeWidths = _strokeSides(json['strokeWidth']),
      fill = _color(json['fill']),
      stroke = _color(json['stroke']),
      text = json['text'] == null ? null : SpecText._(_obj(json['text'])),
      tokens = _tokens(json['tokens']),
      parts = [
        for (final row in _list(json['parts'] ?? const <Object?>[]))
          SpecPart._(_obj(row)),
      ];

  /// The variant name with Figma's ` (Default)` markers stripped, e.g.
  /// `Style=Primary, State=Rest, Size=Medium, Layout=Icon and label`. Every
  /// failure message starts with this.
  final String name;

  /// The untouched Figma layer name, for searching the design file.
  final String figmaName;

  /// The Figma node id, for deep-linking straight to the disagreeing variant.
  final String nodeId;

  /// The variant's property values, e.g. `{'Style': 'Primary', ...}`.
  final Map<String, String> props;

  /// The variant's frame size in Figma. For a hug-content component this is the
  /// size with Figma's own placeholder content, so a component test normally
  /// pins its own content and asserts the height only.
  final Size size;

  /// Content inset from the frame edge, or null when the variant frame carries
  /// no auto-layout and therefore states no padding at all — which is a
  /// different claim from zero. Figma measures this from the *outer* edge and
  /// draws an inside stroke over it, matching CSS `border-box` — see the note
  /// in `test/fixtures/README.md` about bordered variants.
  final EdgeInsets? padding;

  /// Auto-layout item spacing, or null when the variant frame carries no
  /// auto-layout. Not asserted by [expectSpec] — there is no widget every
  /// component is guaranteed to express it through — so assert it against your
  /// own layout widget.
  final double? gap;

  /// Corner radius, already resolved to physical corners.
  final BorderRadius radius;

  /// Border width, or 0 when the variant paints no border. Figma keeps a
  /// stale `strokeWeight` on unstroked nodes; the extractor zeroes it.
  ///
  /// Null when the four sides genuinely disagree — a split button's chevron half
  /// is stroked on three sides and bare on the fourth, and no single number
  /// describes that. Read [strokeWidths] instead; it is always populated.
  final double? strokeWidth;

  /// Border width per side, which is what Figma actually stores. Equal on all
  /// four sides for every component whose [strokeWidth] is non-null.
  final EdgeInsets strokeWidths;

  /// Resolved background, alpha included, or null when the variant has no fill
  /// at all. A fully transparent Fluent token is a real value here
  /// (`0x00FFFFFF`) — never `Colors.transparent`, which stays transparent in
  /// high contrast where the token turns opaque.
  final Color? fill;

  /// Resolved border colour, or null when nothing is stroked.
  final Color? stroke;

  /// Label metrics, or null for variants with no text (icon-only).
  final SpecText? text;

  /// Bound Figma variables, keyed by the property they are bound to —
  /// `fills`, `strokes`, `radius`, `strokeWidth`, `paddingLeft`, `itemSpacing`.
  ///
  /// This is the half of the fixture that matters most. It names the exact
  /// token to select, so nobody reverse-engineers `#0F6CBD` back into
  /// `brandBackground1`, and nobody computes a hover colour from a rest colour.
  final Map<String, List<String>> tokens;

  /// The children under this variant that paint or bind a variable.
  ///
  /// Most components say nothing on the variant frame itself: a Slider's rail
  /// thickness, thumb diameter and every one of its state tokens live three and
  /// four levels down. Empty for a fixture extracted before `parts` existed.
  final List<SpecPart> parts;

  /// The single token bound to [property], or null if none is.
  String? token(String property) => tokens[property]?.first;

  /// The part named [name], e.g. `Thumb`.
  ///
  /// Throws rather than returning null: a missing part means the Figma layer
  /// was renamed, which a test must not quietly skip over.
  SpecPart part(String name) {
    for (final part in parts) {
      if (part.name == name) return part;
    }
    throw StateError(
      '$this has no part named "$name". It has: '
      '${parts.map((p) => p.name).join(', ')}.',
    );
  }

  @override
  String toString() => 'SpecVariant($name)';
}

/// One painted child of a variant: the Slider's `Rail-fill`, the Divider's
/// rule.
///
/// Same numbers as [SpecVariant], minus the ones only a variant frame carries.
/// A property the node does not have at all — a corner radius on a TEXT, an
/// auto-layout padding on a RECTANGLE — is null rather than zero.
class SpecPart {
  SpecPart._(Map<String, dynamic> json)
    : name = _str(json['name']),
      nodeId = _str(json['nodeId']),
      depth = _dbl(json['depth']).toInt(),
      size = Size(
        _dbl(_obj(json['size'])['width']),
        _dbl(_obj(json['size'])['height']),
      ),
      padding = json['padding'] == null
          ? null
          : EdgeInsets.only(
              top: _dbl(_obj(json['padding'])['top']),
              right: _dbl(_obj(json['padding'])['right']),
              bottom: _dbl(_obj(json['padding'])['bottom']),
              left: _dbl(_obj(json['padding'])['left']),
            ),
      gap = json['gap'] == null ? null : _dbl(json['gap']),
      radius = json['radius'] == null ? null : _radius(json['radius']),
      strokeWidth = _uniformStroke(json['strokeWidth']),
      strokeWidths = _strokeSides(json['strokeWidth']),
      fill = _color(json['fill']),
      stroke = _color(json['stroke']),
      tokens = _tokens(json['tokens']),
      text = json['text'] == null ? null : SpecText._(_obj(json['text']));

  /// The Figma layer name, e.g. `Thumb-inner`.
  final String name;

  /// The Figma node id, for deep-linking to the layer.
  final String nodeId;

  /// How far under the variant frame this node sits. 1 is a direct child.
  final int depth;

  /// The node's own size.
  final Size size;

  /// Auto-layout padding, or null when the node has no auto-layout.
  final EdgeInsets? padding;

  /// Auto-layout item spacing, or null when the node has no auto-layout. The
  /// gap between a Radio's indicator and its label lives here, not on the
  /// variant frame.
  final double? gap;

  /// Corner radius, or null when the node type has no corners.
  final BorderRadius? radius;

  /// Border width, or 0 when the node paints no stroke. Null when the four sides
  /// disagree; [strokeWidths] is always populated.
  final double? strokeWidth;

  /// Border width per side, which is what Figma actually stores.
  final EdgeInsets strokeWidths;

  /// Resolved fill, or null when the node has none.
  final Color? fill;

  /// Resolved stroke colour, or null when the node has none.
  final Color? stroke;

  /// Bound Figma variables, keyed by the property they are bound to.
  final Map<String, List<String>> tokens;

  /// This node's own type ramp when it is a TEXT, else null.
  ///
  /// [SpecVariant.text] describes only the *first* text node under the variant,
  /// which is not enough for a component with two independently ramped lines —
  /// a compound button's second line is a different size, weight and colour
  /// from its first.
  final SpecText? text;

  /// The single token bound to [property], or null if none is.
  String? token(String property) => tokens[property]?.first;

  @override
  String toString() => 'SpecPart($name)';
}

/// Label metrics for one variant.
///
/// Deliberately not a rendered glyph box: font size and line height are the
/// only text properties this harness compares.
class SpecText {
  SpecText._(Map<String, dynamic> json)
    : fontFamily = _str(json['fontFamily']),
      fontStyle = _str(json['fontStyle']),
      fontSize = _dbl(json['fontSize']),
      lineHeight = _dbl(json['lineHeight']),
      tokens = _tokens(json['tokens']);

  /// Figma's font family, e.g. `Segoe UI`.
  final String fontFamily;

  /// Figma's style name, e.g. `Semibold`. A name, not a numeric weight — the
  /// bound `Typography/Weight/*` token in [tokens] is the authoritative form.
  final String fontStyle;

  /// Font size in logical pixels.
  final double fontSize;

  /// Line height in logical **pixels**, as Figma states it. Flutter's
  /// `TextStyle.height` is a multiplier, so use [heightMultiplier].
  final double lineHeight;

  /// [lineHeight] as a `TextStyle.height` multiplier.
  double get heightMultiplier => lineHeight / fontSize;

  /// Bound typography variables, keyed by `fontSize`, `lineHeight`,
  /// `fontFamily`, `fontStyle` and `fills`.
  final Map<String, List<String>> tokens;
}

/// Asserts that the widget found by [finder] matches [variant].
///
/// Checks size, padding, corner radius, surface colour, and text metrics, in
/// that order. Each failure names the variant and the property:
///
/// ```text
/// Style=Primary, State=Hover, Size=Medium, Layout=Icon and label:
/// padding.left expected 12, got 10
/// ```
///
/// which is all an agent debugging one of 150 variants has to go on.
///
/// Properties the variant does not define are skipped — an icon-only variant
/// has no [SpecVariant.text], so no text assertion runs. [SpecVariant.gap] is
/// never asserted here; see its doc.
///
/// Reads the widget tree, so a component that paints its surface with a
/// [CustomPaint] rather than a [DecoratedBox] must assert those properties
/// itself. The individual resolvers below are public for exactly that.
void expectSpec(WidgetTester tester, Finder finder, SpecVariant variant) {
  final size = tester.getSize(finder);
  _expectNumber(variant, 'size.width', variant.size.width, size.width);
  _expectNumber(variant, 'size.height', variant.size.height, size.height);

  final expectedPadding = variant.padding;
  if (expectedPadding != null) {
    final padding = _paddingOf(tester, finder, variant);
    _expectNumber(variant, 'padding.top', expectedPadding.top, padding.top);
    _expectNumber(
      variant,
      'padding.right',
      expectedPadding.right,
      padding.right,
    );
    _expectNumber(
      variant,
      'padding.bottom',
      expectedPadding.bottom,
      padding.bottom,
    );
    _expectNumber(variant, 'padding.left', expectedPadding.left, padding.left);
  }

  final radius = resolvedRadiusOf(tester, of: finder);
  if (radius != variant.radius) {
    fail('${variant.name}: radius expected ${variant.radius}, got $radius');
  }

  final expectedFill = variant.fill;
  if (expectedFill != null) {
    final fill = surfaceColorOf(tester, of: finder);
    if (fill.toARGB32() != expectedFill.toARGB32()) {
      fail(
        '${variant.name}: fill expected ${_hex(expectedFill)}, '
        'got ${_hex(fill)} '
        '(token: ${variant.token('fills') ?? 'none'})',
      );
    }
  }

  final text = variant.text;
  if (text == null) return;

  final style = resolvedTextStyleOf(tester, of: finder);
  final fontSize = style.fontSize;
  if (fontSize == null) {
    fail(
      '${variant.name}: text.fontSize expected ${_format(text.fontSize)}, '
      'got no explicit fontSize',
    );
  }
  _expectNumber(variant, 'text.fontSize', text.fontSize, fontSize);

  final height = style.height;
  if (height == null) {
    // Not a nitpick: with no explicit height the metric comes from whichever
    // font the runner happens to load. Fluent states line height explicitly for
    // every ramp step, so must we.
    fail(
      '${variant.name}: text.lineHeight expected ${_format(text.lineHeight)}, '
      'got no explicit height — set TextStyle.height '
      '(${_format(text.lineHeight)} / ${_format(text.fontSize)} = '
      '${text.heightMultiplier.toStringAsFixed(4)}) rather than letting the '
      'font metric decide.',
    );
  }
  _expectNumber(variant, 'text.lineHeight', text.lineHeight, height * fontSize);
}

/// The background colour the widget actually resolved to.
///
/// Reads the first [DecoratedBox] with a coloured [BoxDecoration] under [of],
/// falling back to the first [ColoredBox]. Pass [of] to scope the search;
/// omitting it searches the whole tree.
Color surfaceColorOf(WidgetTester tester, {Finder? of}) {
  for (final box in _under<DecoratedBox>(tester, of)) {
    final decoration = box.decoration;
    if (decoration is BoxDecoration && decoration.color != null) {
      return decoration.color!;
    }
  }
  final colored = _under<ColoredBox>(tester, of);
  if (colored.isNotEmpty) return colored.first.color;
  throw StateError(
    'No DecoratedBox or ColoredBox carrying a colour was found'
    '${of == null ? '' : ' under the given finder'}. A surface painted by a '
    'CustomPaint cannot be read back from the widget tree — such a component '
    'should expose its resolved colour and assert that directly.',
  );
}

/// The corner radius the widget actually resolved to.
///
/// Resolved against [TextDirection.ltr], which is not a shortcut: the fixture's
/// corners are Figma's physical corners, so a physical resolution is the
/// correct comparison even in an RTL test.
BorderRadius resolvedRadiusOf(WidgetTester tester, {Finder? of}) {
  for (final box in _under<DecoratedBox>(tester, of)) {
    final decoration = box.decoration;
    if (decoration is BoxDecoration) {
      return decoration.borderRadius?.resolve(TextDirection.ltr) ??
          BorderRadius.zero;
    }
  }
  throw StateError(
    'No DecoratedBox with a BoxDecoration was found'
    '${of == null ? '' : ' under the given finder'}, so there is no radius to '
    'read. A shape painted by a CustomPaint should be asserted directly.',
  );
}

/// The text style the widget actually painted with.
///
/// Read off [RichText] rather than [Text], because that is where the ambient
/// `DefaultTextStyle` has already been merged in — the value that reaches the
/// rasteriser, not the value the component passed down.
TextStyle resolvedTextStyleOf(WidgetTester tester, {Finder? of}) {
  final texts = _under<RichText>(tester, of);
  if (texts.isEmpty) {
    throw StateError(
      'No Text or RichText was found'
      '${of == null ? '' : ' under the given finder'}.',
    );
  }
  final style = texts.first.text.style;
  if (style == null) {
    throw StateError('The text span carries no style at all.');
  }
  return style;
}

/// The outermost [Padding] under [finder], resolved against the ambient
/// directionality.
///
/// Outermost, because a component that pads twice pads its surface first and
/// its label second, and the fixture describes the surface.
EdgeInsets _paddingOf(WidgetTester tester, Finder finder, SpecVariant variant) {
  final paddings = find.descendant(
    of: finder,
    matching: find.byType(Padding),
    matchRoot: true,
  );
  final widgets = tester.widgetList<Padding>(paddings);
  if (widgets.isEmpty) {
    fail(
      '${variant.name}: no Padding under the finder, so padding cannot be '
      'checked. A component that insets its content another way (a '
      'CustomPaint, an explicit SizedBox) should assert padding itself.',
    );
  }
  final direction =
      Directionality.maybeOf(tester.element(paddings.first)) ??
      TextDirection.ltr;
  return widgets.first.padding.resolve(direction);
}

Iterable<T> _under<T extends Widget>(WidgetTester tester, Finder? of) {
  final matching = find.byType(T);
  return tester.widgetList<T>(
    of == null
        ? matching
        : find.descendant(of: of, matching: matching, matchRoot: true),
  );
}

/// Fails naming the variant and the property, with a tolerance for the float
/// noise layout arithmetic produces (93.99999 is not a spec violation).
void _expectNumber(
  SpecVariant variant,
  String property,
  double expected,
  double actual,
) {
  if ((expected - actual).abs() <= 0.01) return;
  fail(
    '${variant.name}: $property expected ${_format(expected)}, '
    'got ${_format(actual)}',
  );
}

String _format(double value) => value == value.roundToDouble()
    ? value.round().toString()
    : value.toStringAsFixed(2);

String _hex(Color color) =>
    '#${color.toARGB32().toRadixString(16).toUpperCase().padLeft(8, '0')}';

Map<String, dynamic> _obj(Object? value) => value! as Map<String, dynamic>;

List<Object?> _list(Object? value) => value! as List<Object?>;

String _str(Object? value) => value! as String;

double _dbl(Object? value) => (value! as num).toDouble();

Color? _color(Object? value) => value == null
    ? null
    : Color(int.parse(_str(value).substring(1), radix: 16));

/// A uniform stroke width is stored as one number; only a genuinely mixed one
/// is stored per side.
double? _uniformStroke(Object? value) => value is num ? value.toDouble() : null;

EdgeInsets _strokeSides(Object? value) {
  if (value is num) return EdgeInsets.all(value.toDouble());
  final sides = _obj(value);
  return EdgeInsets.only(
    top: _dbl(sides['top']),
    right: _dbl(sides['right']),
    bottom: _dbl(sides['bottom']),
    left: _dbl(sides['left']),
  );
}

/// A uniform radius is stored as one number; only a genuinely mixed one is
/// stored per corner.
BorderRadius _radius(Object? value) {
  if (value is num) return BorderRadius.circular(value.toDouble());
  final corners = _obj(value);
  return BorderRadius.only(
    topLeft: Radius.circular(_dbl(corners['topLeft'])),
    topRight: Radius.circular(_dbl(corners['topRight'])),
    bottomRight: Radius.circular(_dbl(corners['bottomRight'])),
    bottomLeft: Radius.circular(_dbl(corners['bottomLeft'])),
  );
}

Map<String, List<String>> _tokens(Object? value) => {
  for (final entry in _obj(value).entries)
    entry.key: [for (final name in _list(entry.value)) _str(name)],
};
