import 'dart:convert';
import 'dart:io';

import 'package:fluent_2_example/pages.dart';
import 'package:fluent_2_example/shell/catalog.dart';
import 'package:flutter_test/flutter_test.dart';

/// The gate: what we render must match what upstream publishes.
///
/// `test/fixtures/storybook_contract.json` is generated by
/// `crawlers/storybooks-fluentui/capture_docs.mjs` from the Fluent UI React
/// Storybook's own `index.json` and `llms/*.txt`. It is machine-written and
/// never hand-edited, so a section that quietly loses its description, gets
/// retitled, or drifts out of order fails here rather than in review.
///
/// Its hand-written sibling `storybook_adaptations.json` records, with a reason,
/// every section our API cannot express directly. The split is deliberate: a
/// re-capture must not be able to erase the reasoning.
void main() {
  final Map<String, dynamic> contract =
      jsonDecode(
            File('test/fixtures/storybook_contract.json').readAsStringSync(),
          )
          as Map<String, dynamic>;
  final List<Map<String, dynamic>> contractPages =
      (contract['pages'] as List<dynamic>).cast<Map<String, dynamic>>();

  final Map<String, Map<String, dynamic>> byId = <String, Map<String, dynamic>>{
    for (final Map<String, dynamic> p in contractPages)
      (p['pageId'] as String).replaceAll('--docs', ''): p,
  };

  test('every authored page matches its captured sections exactly', () {
    for (final DocsPage page in allPages) {
      final Map<String, dynamic>? captured = byId[page.id];
      expect(
        captured,
        isNotNull,
        reason:
            '${page.id} is not in the contract. Either the id is wrong or the '
            'capture needs re-running.',
      );

      final List<Map<String, dynamic>> sections =
          (captured!['sections'] as List<dynamic>).cast<Map<String, dynamic>>();

      expect(
        page.sections.map((DocsSection s) => s.id).toList(),
        sections.map((Map<String, dynamic> s) => s['storyId']).toList(),
        reason:
            '${page.id}: section ids differ from upstream, or are out of order. '
            'Upstream order is declaration order, which is what the docs page '
            'renders — not the alphabetical order llms.txt lists.',
      );

      for (int i = 0; i < page.sections.length; i += 1) {
        expect(
          page.sections[i].title,
          sections[i]['title'],
          reason:
              '${page.sections[i].id}: title differs from the rendered <h3> '
              'upstream. Titles are verbatim, punctuation included.',
        );
      }
    }
  });

  test('theme pages carry a body instead of sections', () {
    for (final DocsPage page in allPages.where(
      (DocsPage p) => p.id.startsWith('theme-'),
    )) {
      expect(
        page.sections,
        isEmpty,
        reason: '${page.id}: upstream Theme pages publish no stories',
      );
      expect(
        page.body,
        isNotNull,
        reason: '${page.id}: a Theme page with no body renders an empty page',
      );
    }
  });

  // The work queue. Red until the port is finished, then a regression guard
  // against a page being dropped from the registry.
  test('every captured page is implemented', () {
    final Set<String> authored = allPages.map((DocsPage p) => p.id).toSet();
    final List<String> missing =
        byId.keys.where((String id) => !authored.contains(id)).toList()..sort();

    expect(
      missing,
      isEmpty,
      reason:
          '${missing.length} of ${byId.length} captured pages are not yet '
          'implemented:\n  ${missing.join('\n  ')}',
    );
  });
}
